(function(){
'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const uid=()=>Math.random().toString(36).slice(2,10);
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const SVGNS='http://www.w3.org/2000/svg';
const FIG_W=1200, FIG_H=800;
const palette=['#2563eb','#f97316','#16a34a','#dc2626','#7c3aed','#0891b2','#ca8a04','#475569'];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const SUBSCRIPT_MAP={'0':'₀','1':'₁','2':'₂','3':'₃','4':'₄','5':'₅','6':'₆','7':'₇','8':'₈','9':'₉','+':'₊','-':'₋','−':'₋','=':'₌','(':'₍',')':'₎'};
const SUPERSCRIPT_MAP={'0':'⁰','1':'¹','2':'²','3':'³','4':'⁴','5':'⁵','6':'⁶','7':'⁷','8':'⁸','9':'⁹','+':'⁺','-':'⁻','−':'⁻','=':'⁼','(':'⁽',')':'⁾'};
const SCRIPT_NORMAL_MAP=Object.fromEntries([...Object.entries(SUBSCRIPT_MAP),...Object.entries(SUPERSCRIPT_MAP)].map(([normal,script])=>[script,normal==='−'?'-':normal]));
function svgEl(name,attrs={},text){const n=document.createElementNS(SVGNS,name);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(text!==undefined)n.textContent=text;return n}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},800)}
function niceTicks(min,max,n=5){if(!Number.isFinite(min)||!Number.isFinite(max)||min===max)return[min];const raw=(max-min)/Math.max(1,n-1),p=Math.pow(10,Math.floor(Math.log10(Math.abs(raw)||1))),e=raw/p,candidates=[1,2,2.5,5,10],m=candidates.reduce((best,v)=>Math.abs(Math.log(v/e))<Math.abs(Math.log(best/e))?v:best,1),step=m*p,start=Math.ceil(min/step)*step,out=[];for(let x=start;x<=max+step*.15;x+=step)out.push(+x.toPrecision(12));return out.length?out:[min,max]}
function cleanManualLimit(value,axis,span){if(!Number.isFinite(value))return value;if(axis==='x')return Math.round(value*10)/10;const range=Math.abs(span);if(range>=10)return Math.round(value);if(range>=1)return Math.round(value*10)/10;return Number(value.toPrecision(4))}
function exactTicks(min,max,n){n=clamp(Math.round(Number(n)||2),2,50);const raw=Math.abs(max-min)/Math.max(1,n-1),decimals=raw>=1?0:clamp(Math.ceil(-Math.log10(raw||1))+1,0,10),factor=10**decimals,out=Array.from({length:n},(_,i)=>clamp(Math.round((min+(max-min)*i/(n-1))*factor)/factor,min,max));for(let i=1;i<out.length;i++)if(out[i]<=out[i-1])return Array.from({length:n},(_,j)=>+(min+(max-min)*j/(n-1)).toPrecision(12));return out}
function steppedTicks(min,max,step,first){step=Math.abs(Number(step));if(!Number.isFinite(step)||step<=0)return niceTicks(min,max,6);let start=Number(first);if(!Number.isFinite(start))start=Math.ceil(min/step)*step;while(start-step>=min-1e-10)start-=step;while(start<min-1e-10)start+=step;const out=[];for(let v=start;v<=max+step*1e-9&&out.length<500;v+=step)out.push(+v.toPrecision(12));return out.length?out:[min,max]}
function ticksFor(p,axis,min,max){const mode=p[axis+'TickMode']||'auto';if(mode==='count')return exactTicks(min,max,p[axis+'TickCount']);if(mode==='step')return steppedTicks(min,max,p[axis+'TickStep'],p[axis+'TickFirst']);return niceTicks(min,max,p[axis+'TickCount']||6)}
function splitDelimited(line,d){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===d&&!q){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out}
function numericValue(v){const raw=String(v??'').trim();if(!raw)return null;const n=Number(raw.replace(/\s/g,'').replace(',','.'));return Number.isFinite(n)?n:null}
function findTable(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(l=>l.trim());if(lines.length<2)throw new Error('The file has no tabular data rows.');let best=null;for(const d of ['\t',';',','])for(let start=0;start<=Math.min(lines.length-2,100);start++){const first=splitDelimited(lines[start],d);if(first.length<2)continue;const cols=first.length;let consistent=0,numeric=0,cells=0;for(let j=start+1;j<Math.min(lines.length,start+10);j++){const p=splitDelimited(lines[j],d);if(p.length!==cols)continue;consistent++;p.forEach(cell=>{cells++;if(numericValue(cell)!==null)numeric++})}if(!consistent)continue;const density=cells?numeric/cells:0,score=consistent*12+density*30+Math.min(cols,14)-start*.12;if(!best||score>best.score)best={delimiter:d,start,cols,score}}if(!best)throw new Error('No CSV/TSV table could be detected.');return{lines,...best}}
function parseCSV(text,name){const {lines,delimiter,start,cols}=findTable(text),first=splitDelimited(lines[start],delimiter),numericFirst=first.filter(v=>numericValue(v)!==null).length,firstIsData=numericFirst>=Math.ceil(cols*.6),headers=firstIsData?first.map((_,i)=>`Column ${i+1}`):first.map((h,i)=>h||`Column ${i+1}`),rows=[];for(const line of lines.slice(firstIsData?start:start+1)){const p=splitDelimited(line,delimiter);if(p.length!==cols)continue;const row=p.map(v=>numericValue(v)??v);if(row.filter(v=>typeof v==='number').length<Math.min(2,cols))continue;rows.push(headers.map((_,i)=>row[i]??''))}if(!rows.length)throw new Error('A table was found, but no numeric X/Y rows could be read.');return{id:uid(),name:name.replace(/\.(csv|txt|tsv)$/i,''),headers,rows,delimiter,sourceFile:name}}
function defaultPanel(x=80,y=60,w=1040,h=660){return{id:uid(),x,y,w,h,gridRow:null,gridCol:null,reverseX:true,reverseY:false,locked:false,xScale:'tight',xMin:null,xMax:null,yScale:'tight',yMin:null,yMax:null,xTickMode:'auto',yTickMode:'auto',xTickCount:6,yTickCount:5,xTickStep:1,yTickStep:1,xTickFirst:null,yTickFirst:null,xMinorTicks:0,yMinorTicks:0,xTickLength:6,yTickLength:6,xMinorLength:3.5,yMinorLength:3.5,xTickWidth:1,yTickWidth:1,xTickColor:'#111111',yTickColor:'#111111',xTickLabelSize:12,yTickLabelSize:12,xTickLabelColor:'#111111',yTickLabelColor:'#111111',xTickLabelBold:false,yTickLabelBold:false,xTickLabelItalic:false,yTickLabelItalic:false,xLabelOffsetY:0,yLabelOffsetX:0,sides:{top:true,right:true,bottom:true,left:true},xTicks:true,xLabels:true,yTicks:false,yLabels:false,curves:[],annotations:[]}}
function blankFigure(name='Figure 1'){return{id:uid(),name,width:FIG_W,height:FIG_H,rows:1,cols:1,gapX:0,gapY:0,xLinkMode:'independent',yLinkMode:'independent',panels:[defaultPanel()],annotations:[]}}
const state={datasets:[],figures:[blankFigure()],activeFigure:0,selectedPanelId:null,selectedCurveId:null,selectedAnnotation:null,selectedTickLabels:null,canvasSelection:'panel',editorDatasetId:null,panelDatasetPanelId:null,dataMode:false,geomUnit:'px',stackLevel:0,snapGuides:[],drawingShape:null};
let annotationClipboard=null;
let shapeDefaults={scope:'panel',color:'#111111',width:1.5,lineStyle:'solid',startCap:'none',endCap:'arrow'};
state.selectedPanelId=state.figures[0].panels[0].id;
const editHistory={past:[],future:[],present:null,timer:null,locked:false,limit:10};
const AUTOSAVE_DB='xps-figure-builder',AUTOSAVE_STORE='drafts',AUTOSAVE_KEY='current';
let autosaveReady=false,autosaveDbPromise=null,autosaveTimer=null,pendingAutosave=null,lastAutosavedSnapshot=null,lastAutosaveDirty=null;
function projectSnapshot(){return JSON.stringify({datasets:state.datasets,figures:state.figures,activeFigure:state.activeFigure,stackLevel:state.stackLevel||0})}
function setAutosaveStatus(text,error=false){const el=$('#autosaveStatus');if(!el)return;el.textContent=text;el.classList.toggle('error',error)}
function autosaveTime(iso){try{return new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit'}).format(new Date(iso))}catch{return''}}
function openAutosaveDb(){if(autosaveDbPromise)return autosaveDbPromise;autosaveDbPromise=new Promise((resolve,reject)=>{if(!window.indexedDB){reject(new Error('IndexedDB unavailable'));return}const request=indexedDB.open(AUTOSAVE_DB,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(AUTOSAVE_STORE))db.createObjectStore(AUTOSAVE_STORE,{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('Autosave database unavailable'))});return autosaveDbPromise}
async function readAutosaveDraft(){const db=await openAutosaveDb();return new Promise((resolve,reject)=>{const tx=db.transaction(AUTOSAVE_STORE,'readonly'),request=tx.objectStore(AUTOSAVE_STORE).get(AUTOSAVE_KEY);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error)})}
async function deleteAutosaveDraft(){const db=await openAutosaveDb();return new Promise((resolve,reject)=>{const tx=db.transaction(AUTOSAVE_STORE,'readwrite');tx.objectStore(AUTOSAVE_STORE).delete(AUTOSAVE_KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
async function persistAutosave(snapshot,dirty=true){const db=await openAutosaveDb(),savedAt=new Date().toISOString();await new Promise((resolve,reject)=>{const tx=db.transaction(AUTOSAVE_STORE,'readwrite');tx.objectStore(AUTOSAVE_STORE).put({id:AUTOSAVE_KEY,savedAt,dirty,payload:{kind:'xpsfig-autosave',version:1,state:JSON.parse(snapshot)}});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)});lastAutosavedSnapshot=snapshot;lastAutosaveDirty=dirty;setAutosaveStatus(`${dirty?'Autosaved':'Project saved'} · ${autosaveTime(savedAt)}`)}
function scheduleAutosave(snapshot=projectSnapshot(),dirty=true,delay=450){if(!autosaveReady)return;if(snapshot===lastAutosavedSnapshot&&dirty===lastAutosaveDirty)return;pendingAutosave={snapshot,dirty};clearTimeout(autosaveTimer);setAutosaveStatus('Saving…');autosaveTimer=setTimeout(flushAutosave,delay)}
async function flushAutosave(){if(!autosaveReady||!pendingAutosave)return;clearTimeout(autosaveTimer);autosaveTimer=null;const job=pendingAutosave;pendingAutosave=null;try{await persistAutosave(job.snapshot,job.dirty)}catch{setAutosaveStatus('Autosave unavailable',true)}}
async function markProjectSaved(){if(!autosaveReady)return;pendingAutosave={snapshot:projectSnapshot(),dirty:false};await flushAutosave()}
function flushCurrentAutosave(){commitHistory();flushAutosave()}
function updateHistoryButtons(){const undo=$('#undoAction'),redo=$('#redoAction');if(undo)undo.disabled=!editHistory.past.length;if(redo)redo.disabled=!editHistory.future.length}
function commitHistory(){if(editHistory.locked)return;clearTimeout(editHistory.timer);editHistory.timer=null;const next=projectSnapshot();if(next===editHistory.present)return;if(editHistory.present!==null){editHistory.past.push(editHistory.present);if(editHistory.past.length>editHistory.limit)editHistory.past.shift()}editHistory.present=next;editHistory.future=[];updateHistoryButtons();scheduleAutosave(next,true)}
function scheduleHistoryCommit(delay=0){if(editHistory.locked)return;clearTimeout(editHistory.timer);editHistory.timer=setTimeout(commitHistory,delay)}
function restoreHistorySnapshot(snapshot){editHistory.locked=true;const saved=JSON.parse(snapshot);state.datasets=saved.datasets||[];state.figures=saved.figures||[blankFigure()];state.activeFigure=saved.activeFigure||0;state.stackLevel=saved.stackLevel||0;state.drawingShape=null;normalizeLoadedState();updateDataUI();syncUI();render();editHistory.present=snapshot;editHistory.locked=false;updateHistoryButtons();scheduleAutosave(snapshot,true)}
function undoProject(){commitHistory();if(!editHistory.past.length)return;editHistory.future.push(editHistory.present);restoreHistorySnapshot(editHistory.past.pop())}
function redoProject(){commitHistory();if(!editHistory.future.length)return;editHistory.past.push(editHistory.present);restoreHistorySnapshot(editHistory.future.pop())}
function resetProjectHistory(){clearTimeout(editHistory.timer);editHistory.timer=null;editHistory.past=[];editHistory.future=[];editHistory.present=projectSnapshot();updateHistoryButtons()}
function fig(){return state.figures[state.activeFigure]}
function panel(){return fig().panels.find(p=>p.id===state.selectedPanelId)||fig().panels[0]}
function curve(){const p=panel();return p?.curves.find(c=>c.id===state.selectedCurveId)}
function datasetById(id){return state.datasets.find(d=>d.id===id)}
function currentDataset(){return datasetById($('#datasetSelect').value)||state.datasets[0]}
function editorDataset(){return datasetById(state.editorDatasetId)||state.datasets[0]}
function ensurePanel(p){p.sides=p.sides||{top:true,right:true,bottom:true,left:true};p.gridRow=p.gridRow??null;p.gridCol=p.gridCol??null;p.reverseX=p.reverseX!==false;p.reverseY=!!p.reverseY;p.xTicks=p.xTicks!==false;p.xLabels=p.xLabels!==false;p.yTicks=!!p.yTicks;p.yLabels=!!p.yLabels;p.xScale=p.xScale||'tight';p.xMin=p.xMin??null;p.xMax=p.xMax??null;p.yScale=p.yScale||'tight';p.yMin=p.yMin??null;p.yMax=p.yMax??null;p.xTickMode=p.xTickMode||'auto';p.yTickMode=p.yTickMode||'auto';p.xTickCount=p.xTickCount||6;p.yTickCount=p.yTickCount||5;p.xTickStep=p.xTickStep??1;p.yTickStep=p.yTickStep??1;p.xTickFirst=p.xTickFirst??null;p.yTickFirst=p.yTickFirst??null;p.xMinorTicks=p.xMinorTicks??0;p.yMinorTicks=p.yMinorTicks??0;p.xTickLength=p.xTickLength??p.tickLength??6;p.yTickLength=p.yTickLength??p.tickLength??6;p.xMinorLength=p.xMinorLength??Math.max(1,p.xTickLength*.6);p.yMinorLength=p.yMinorLength??Math.max(1,p.yTickLength*.6);p.xTickWidth=p.xTickWidth??p.tickWidth??1;p.yTickWidth=p.yTickWidth??p.tickWidth??1;p.xTickColor=p.xTickColor||p.tickColor||'#111111';p.yTickColor=p.yTickColor||p.tickColor||'#111111';p.xTickLabelSize=p.xTickLabelSize||p.tickLabelSize||12;p.yTickLabelSize=p.yTickLabelSize||p.tickLabelSize||12;p.xTickLabelColor=p.xTickLabelColor||p.tickLabelColor||'#111111';p.yTickLabelColor=p.yTickLabelColor||p.tickLabelColor||'#111111';p.xTickLabelBold=p.xTickLabelBold??!!p.tickLabelBold;p.yTickLabelBold=p.yTickLabelBold??!!p.tickLabelBold;p.xTickLabelItalic=p.xTickLabelItalic??!!p.tickLabelItalic;p.yTickLabelItalic=p.yTickLabelItalic??!!p.tickLabelItalic;p.xLabelOffsetY=p.xLabelOffsetY||0;p.yLabelOffsetX=p.yLabelOffsetX||0;p.annotations=p.annotations||[];p.curves=p.curves||[];p.curves.forEach(ensureCurve);return p}
function ensureCurve(c){c.label=c.label||'Curve';c.role=c.role||'generic';c.color=c.color||'#2563eb';c.lineWidth=c.lineWidth??1.8;c.lineStyle=c.lineStyle||'solid';c.markerStyle=c.markerStyle||'none';c.markerSize=c.markerSize??3.5;c.markerColor=c.markerColor||c.color;c.fillMode=c.fillMode||'none';c.fillOpacity=c.fillOpacity??.62;c.visible=c.visible!==false;c.offset=c.offset||0;return c}
function normalizeLoadedState(){state.figures.forEach(f=>{f.width=f.width||FIG_W;f.height=f.height||FIG_H;f.rows=f.rows||1;f.cols=f.cols||1;f.gapX=f.gapX??12;f.gapY=f.gapY??12;f.xLinkMode=f.xLinkMode||f.panels?.[0]?.xMode||'independent';f.yLinkMode=f.yLinkMode||f.panels?.[0]?.yMode||'independent';f.annotations=f.annotations||[];f.panels=(f.panels||[]).map(ensurePanel)});if(!state.figures.length)state.figures=[blankFigure()];state.activeFigure=clamp(state.activeFigure||0,0,state.figures.length-1);state.selectedPanelId=fig().panels[0]?.id||null;state.selectedCurveId=null;state.selectedAnnotation=null;state.selectedTickLabels=null;state.canvasSelection='panel';state.editorDatasetId=datasetById(state.editorDatasetId)?.id||state.datasets[0]?.id||null;state.panelDatasetPanelId=null;state.geomUnit=state.geomUnit||'px';state.snapGuides=[]}
function applyProjectState(saved){Object.keys(state).forEach(key=>delete state[key]);Object.assign(state,saved);normalizeLoadedState();updateDataUI();syncUI();render()}
function setOptions(sel,opts,value){sel.innerHTML=opts.map(o=>`<option value="${esc(o.value)}">${esc(o.label)}</option>`).join('');if(value!==undefined&&value!==null&&opts.some(o=>String(o.value)===String(value)))sel.value=value}
function updateDataUI(){
  const ds=$('#datasetSelect'),old=ds.value;
  setOptions(ds,state.datasets.map(d=>({value:d.id,label:d.name})),old);
  const d=currentDataset();
  $('#dataSummary').textContent=state.datasets.length?`${state.datasets.length} dataset${state.datasets.length>1?'s':''} in project`:'No data loaded';
  const oldX=$('#xSelect').value;
  setOptions($('#xSelect'),d?d.headers.map((h,i)=>({value:i,label:h})):[],oldX||'0');
  const top=$('#topDatasetSelect');
  if(top)setOptions(top,state.datasets.map(x=>({value:x.id,label:x.name})),editorDataset()?.id);
  $('#deleteDatasetTop').disabled=!editorDataset();$('#renameDataset').disabled=!editorDataset();
  renderYMenu();
  $('#addCurve').disabled=!d;
  if(state.dataMode)renderDataTable();
}
function setPanelDataset(id,xIndex=null){const d=datasetById(id);if(!d)return;$('#datasetSelect').value=d.id;const oldX=xIndex===null?$('#xSelect').value:String(xIndex);setOptions($('#xSelect'),d.headers.map((h,i)=>({value:i,label:h})),oldX);renderYMenu()}
function syncDatasetForPanel(){const p=panel();if(!p||state.panelDatasetPanelId===p.id)return;const c=p.curves.find(x=>x.id===state.selectedCurveId)||p.curves[0];if(c&&datasetById(c.datasetId))setPanelDataset(c.datasetId,c.xIndex);state.panelDatasetPanelId=p.id}
function renderYMenu(){
  const d=currentDataset(),menu=$('#yMultiMenu');
  if(!d){menu.innerHTML='';$('#yMultiButton').textContent='Select Y columns';return}
  const x=Number($('#xSelect').value||0),p=panel(),present=new Set((p?.curves||[]).filter(c=>c.datasetId===d.id&&c.xIndex===x).map(c=>c.yIndex));
  menu.innerHTML='';
  d.headers.forEach((h,i)=>{
    if(i===x)return;
    const lab=document.createElement('label'),cb=document.createElement('input');
    cb.type='checkbox';cb.value=i;cb.checked=present.has(i);
    cb.addEventListener('change',()=>{updateYButton();$('#addCurve').disabled=!currentDataset()});
    lab.append(cb,document.createTextNode(h));menu.appendChild(lab)
  });
  updateYButton();
}
function getSelectedY(){return $$('#yMultiMenu input:checked').map(x=>Number(x.value))}
function updateYButton(){const d=currentDataset(),ys=getSelectedY();if(!d||!ys.length){$('#yMultiButton').textContent='Select Y columns';return}$('#yMultiButton').textContent=ys.length===1?d.headers[ys[0]]:`${ys.length} Y columns selected`}
function inferStyle(header,index){const s=header.toLowerCase();if(s.includes('background'))return{role:'background',color:'#111111',lineStyle:'solid',lineWidth:1,markerStyle:'none',fillMode:'none'};if(s.includes('envelope'))return{role:'fit',color:'#111111',lineStyle:'solid',lineWidth:1,markerStyle:'none',fillMode:'none'};if(s.includes('cps')||s.includes('counts'))return{role:'raw',color:'#111111',lineStyle:'none',lineWidth:0,markerStyle:'circle',markerSize:3,fillMode:'none'};return{role:'generic',color:'#111111',lineStyle:'solid',lineWidth:1,markerStyle:'none',fillMode:'none'}}
function applySelectedY(){const d=currentDataset(),p=panel();if(!d||!p)return;const xi=Number($('#xSelect').value),ys=new Set(getSelectedY());p.curves=p.curves.filter(c=>c.datasetId!==d.id||c.xIndex!==xi||ys.has(c.yIndex));ys.forEach((yi,k)=>{if(p.curves.some(c=>c.datasetId===d.id&&c.xIndex===xi&&c.yIndex===yi))return;const st=inferStyle(d.headers[yi],p.curves.length+k),c=ensureCurve({id:uid(),datasetId:d.id,xIndex:xi,yIndex:yi,label:d.headers[yi],...st,markerColor:st.color,fillOpacity:.65,backgroundId:null,offset:0});const bg=p.curves.find(q=>q.role==='background');if(c.role==='generic'&&bg&&/(_\d+_|component|peak)/i.test(c.label)){c.role='component';c.fillMode='background';c.backgroundId=bg.id}p.curves.push(c);state.selectedCurveId=c.id});if(state.selectedCurveId&&!p.curves.some(c=>c.id===state.selectedCurveId))state.selectedCurveId=p.curves[0]?.id||null;if(p.curves.length)$('#curvesSection').open=true;syncUI();render()}
function removeSelectedDataset(){const d=editorDataset();if(!d)return;let used=0;state.figures.forEach(f=>f.panels.forEach(p=>p.curves.forEach(c=>{if(c.datasetId===d.id)used++})));const detail=used?` It is used by ${used} curve${used>1?'s':''}, which will also be removed.`:' It is not used by any panel.';if(!confirm(`Delete dataset “${d.name}”?${detail}`))return;state.datasets=state.datasets.filter(x=>x.id!==d.id);state.figures.forEach(f=>f.panels.forEach(p=>{p.curves=p.curves.filter(c=>c.datasetId!==d.id)}));state.editorDatasetId=state.datasets[0]?.id||null;state.panelDatasetPanelId=null;state.selectedCurveId=null;updateDataUI();syncUI();render()}
function applyGrid(){
  const f=fig(),rows=clamp(Number($('#gridRows').value)||1,1,6),cols=clamp(Number($('#gridCols').value)||1,1,6),count=rows*cols;
  f.gapX=Math.max(0,Number($('#gapX').value)||0);f.gapY=Math.max(0,Number($('#gapY').value)||0);
  const marginL=64,marginR=54,marginT=38,marginB=62,gx=f.gapX,gy=f.gapY,w=(f.width-marginL-marginR-gx*(cols-1))/cols,h=(f.height-marginT-marginB-gy*(rows-1))/rows;
  f.rows=rows;f.cols=cols;
  while(f.panels.length<count)f.panels.push(defaultPanel());
  f.panels.slice(0,count).forEach((p,i)=>{
    const r=Math.floor(i/cols),c=i%cols;
    p.x=marginL+c*(w+gx);p.y=marginT+r*(h+gy);p.w=w;p.h=h;p.gridRow=r;p.gridCol=c;
    p.sides={top:true,right:true,bottom:true,left:true};p.xTicks=true;p.xLabels=r===rows-1;p.yTicks=false;p.yLabels=false;
  });
  f.panels.slice(count).forEach(p=>{p.gridRow=null;p.gridCol=null});
  if(!f.panels.some(p=>p.id===state.selectedPanelId))state.selectedPanelId=f.panels[0]?.id||null;
  state.selectedCurveId=null;state.selectedAnnotation=null;state.selectedTickLabels=null;state.canvasSelection='panel';syncUI();render();
}
function displayGeom(v,axis){if(state.geomUnit==='px')return Math.round(v*10)/10;const base=(axis==='x'||axis==='w')?fig().width:fig().height;return Math.round((v/base*100)*10)/10}
function fromDisplay(v,axis){const n=Number(v);if(!Number.isFinite(n))return null;if(state.geomUnit==='px')return n;const base=(axis==='x'||axis==='w')?fig().width:fig().height;return n/100*base}
function linkLabel(mode,axis){return mode==='all'?'All panels':mode==='column'?'Same column':mode==='row'?'Same row':'Independent'}
function syncUI(){
  const f=fig(),p=panel();
  $('#canvasW').value=Math.round(f.width);$('#canvasH').value=Math.round(f.height);$('#gridRows').value=f.rows||1;$('#gridCols').value=f.cols||1;$('#gapX').value=f.gapX;$('#gapY').value=f.gapY;
  $$('[data-unit]').forEach(b=>b.classList.toggle('active',b.dataset.unit===state.geomUnit));renderTabs();
  if(!p)return;
  syncDatasetForPanel();
  const panelLabel=`Panel ${f.panels.indexOf(p)+1}`;$('#panelName').textContent=panelLabel;$('#axesPanelBadge').textContent=panelLabel;
  [['panelX','x','x'],['panelY','y','y'],['panelW','w','w'],['panelH','h','h']].forEach(([id,key,axis])=>{$('#'+id).value=displayGeom(p[key],axis)});
  $('#xAxisMode').value=f.xLinkMode||'independent';$('#yAxisMode').value=f.yLinkMode||'independent';$('#xLinkStatus').textContent=`X · ${linkLabel(f.xLinkMode,'x')}`;$('#yLinkStatus').textContent=`Y · ${linkLabel(f.yLinkMode,'y')}`;$('#reverseX').checked=p.reverseX;$('#reverseY').checked=p.reverseY;$('#lockPanel').checked=p.locked;$('#xTicks').checked=p.xTicks;$('#xLabels').checked=p.xLabels;$('#yTicks').checked=p.yTicks;$('#yLabels').checked=p.yLabels;
  Object.keys(p.sides).forEach(s=>$('#border'+s[0].toUpperCase()+s.slice(1)).classList.toggle('active',p.sides[s]));
  $$('[data-xscale]').forEach(b=>b.classList.toggle('active',b.dataset.xscale===p.xScale));$('#xMin').value=p.xMin??'';$('#xMax').value=p.xMax??'';$('#xMin').disabled=p.xScale!=='manual';$('#xMax').disabled=p.xScale!=='manual';
  $$('[data-yscale]').forEach(b=>b.classList.toggle('active',b.dataset.yscale===p.yScale));$('#yMin').value=p.yMin??'';$('#yMax').value=p.yMax??'';$('#yMin').disabled=p.yScale!=='manual';$('#yMax').disabled=p.yScale!=='manual';
  const visibleRange=rangesFor(p),yInputStep=Math.max(Math.abs(visibleRange.y1-visibleRange.y0)/100,1e-9);$('#yMin').step=$('#yMax').step=String(+yInputStep.toPrecision(3));
  ['x','y'].forEach(axis=>{const cap=axis.toUpperCase(),offset=p[axis==='x'?'xLabelOffsetY':'yLabelOffsetX']||0,mode=p[axis+'TickMode']||'auto';$('#'+axis+'TickMode').value=mode;document.querySelector(`[data-axis-card="${axis}"]`).dataset.tickMode=mode;$('#'+axis+'TickCount').value=p[axis+'TickCount'];$('#'+axis+'TickStep').value=p[axis+'TickStep']??'';$('#'+axis+'TickFirst').value=p[axis+'TickFirst']??'';$('#'+axis+'MinorTicks').value=p[axis+'MinorTicks'];$('#'+axis+'TickLength').value=p[axis+'TickLength'];$('#'+axis+'MinorLength').value=p[axis+'MinorLength'];$('#'+axis+'TickWidth').value=p[axis+'TickWidth'];$('#'+axis+'TickColor').value=p[axis+'TickColor'];$('#'+axis+'TickLabelSize').value=p[axis+'TickLabelSize'];$('#'+axis+'TickLabelColor').value=p[axis+'TickLabelColor'];$('#'+axis+'TickLabelBold').classList.toggle('active',p[axis+'TickLabelBold']);$('#'+axis+'TickLabelItalic').classList.toggle('active',p[axis+'TickLabelItalic']);$('#'+axis+'LabelOffsetValue').textContent=`${offset>0?'+':''}${Math.round(offset)} px`;$('#reset'+cap+'LabelOffset').disabled=Math.abs(offset)<.5});
  renderYMenu();renderCurveList();renderAnnotationList()
}
function renderTabs(){const wrap=$('#figureTabs');wrap.innerHTML='';state.figures.forEach((f,i)=>{const b=document.createElement('button');b.className='figureTab'+(i===state.activeFigure?' active':'');b.textContent=f.name;b.onclick=()=>{state.activeFigure=i;state.selectedPanelId=fig().panels[0]?.id||null;state.selectedCurveId=null;state.selectedAnnotation=null;state.selectedTickLabels=null;state.canvasSelection='panel';showDataMode(false);syncUI();render()};wrap.appendChild(b)})}
function renderCurveList(){
  const p=panel(),wrap=$('#curveList');
  const panelNo=p?fig().panels.indexOf(p)+1:0,count=p?.curves.length||0,sources=[...new Set((p?.curves||[]).map(c=>{const d=datasetById(c.datasetId);return d?.sourceFile&&d.sourceFile!=='Pasted data'?d.sourceFile:d?.name}).filter(Boolean))];$('#curvesPanelBadge').textContent=`Panel ${panelNo}`;$('#panelContentsSummary').innerHTML=count?`<strong>Panel ${panelNo} · ${count} curve${count>1?'s':''}</strong><span title="${esc(sources.join(' · '))}">${esc(sources.join(' · '))}</span>`:`<strong>Panel ${panelNo}</strong><span>No data source</span>`;
  if(!p?.curves.length){wrap.innerHTML='<div class="microText">No curve in this panel.</div>';$('#curveEditor').classList.add('hidden');return}
  wrap.innerHTML='';
  p.curves.forEach((c,i)=>{
    const row=document.createElement('div');
    row.className='curveItem'+(c.id===state.selectedCurveId?' active':'');row.draggable=true;row.dataset.curveId=c.id;
    row.innerHTML=`<span class="curveDrag" title="Drag to change draw order">⠿</span><span class="curveSwatch" style="background:${c.color}"></span><span class="curveName">${esc(c.label)}</span><button class="curveMiniBtn vis" title="Show / hide">${c.visible===false?'○':'●'}</button><button class="curveMiniBtn del" title="Remove">×</button>`;
    row.onclick=e=>{if(e.target.closest('button'))return;state.selectedCurveId=c.id;setPanelDataset(c.datasetId,c.xIndex);state.panelDatasetPanelId=p.id;renderCurveList()};
    row.querySelector('.vis').onclick=()=>{c.visible=!c.visible;renderCurveList();render()};
    row.querySelector('.del').onclick=()=>{p.curves=p.curves.filter(x=>x.id!==c.id);if(state.selectedCurveId===c.id)state.selectedCurveId=p.curves[0]?.id||null;renderCurveList();render()};
    row.ondragstart=e=>{row.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',c.id)};
    row.ondragend=()=>{$$('.curveItem').forEach(x=>x.classList.remove('dragging','dragOver'))};
    row.ondragover=e=>{e.preventDefault();row.classList.add('dragOver');e.dataTransfer.dropEffect='move'};
    row.ondragleave=()=>row.classList.remove('dragOver');
    row.ondrop=e=>{e.preventDefault();row.classList.remove('dragOver');const dragged=e.dataTransfer.getData('text/plain');if(!dragged||dragged===c.id)return;const from=p.curves.findIndex(x=>x.id===dragged),to=p.curves.findIndex(x=>x.id===c.id);if(from<0||to<0)return;const [m]=p.curves.splice(from,1);p.curves.splice(to,0,m);state.selectedCurveId=dragged;renderCurveList();render()};
    wrap.appendChild(row)
  });
  if(!curve())state.selectedCurveId=p.curves[0].id;
  const c=curve();if(!c)return;
  $('#curveEditor').classList.remove('hidden');$('#curveName').value=c.label;$('#curveRole').value=c.role;$('#lineStyle').value=c.lineStyle;$('#lineWidth').value=c.lineWidth;$('#curveColor').value=c.color;$('#markerStyle').value=c.markerStyle;$('#markerSize').value=c.markerSize;$('#markerColor').value=c.markerColor;$('#fillMode').value=c.fillMode;$('#fillOpacity').value=Math.round(c.fillOpacity*100);
  const backs=p.curves.filter(x=>x.id!==c.id&&x.role==='background');setOptions($('#backgroundSelect'),backs.map(x=>({value:x.id,label:x.label})),c.backgroundId||backs[0]?.id);$('#backgroundField').classList.toggle('hidden',c.fillMode!=='background')
}
function allAnnotations(){const p=panel();return[...(p?.annotations||[]).map(a=>({a,scope:'panel'})),...fig().annotations.map(a=>({a,scope:'figure'}))]}
function selectedAnnotationObj(){if(!state.selectedAnnotation)return null;const {id,scope,panelId}=state.selectedAnnotation,owner=scope==='panel'?fig().panels.find(p=>p.id===panelId)||panel():null,src=scope==='panel'?owner?.annotations:fig().annotations,a=src?.find(x=>x.id===id);return a?{a,scope,owner}:null}
function formatInputSelection(input,mode,onChange){const start=input.selectionStart,end=input.selectionEnd;if(start===null||end===null||start===end)return;const map=mode==='sub'?SUBSCRIPT_MAP:SUPERSCRIPT_MAP,selected=input.value.slice(start,end),chars=Array.from(selected),convertible=chars.filter(ch=>map[SCRIPT_NORMAL_MAP[ch]||ch]);if(!convertible.length)return;const already=convertible.every(ch=>Object.values(map).includes(ch)),replacement=chars.map(ch=>{const normal=SCRIPT_NORMAL_MAP[ch]||ch;return map[normal]?(already?normal:map[normal]):ch}).join('');input.setRangeText(replacement,start,end,'select');onChange(input.value);input.focus()}
function ensureLegendEntry(e){e.color=e.color||'#111111';e.bold=!!e.bold;e.italic=!!e.italic;e.visible=e.visible!==false;return e}
function legendEntries(a,owner){if(a.mode==='manual'){if(!a.manualEntries){const old=String(a.text||'').split('\n').filter(Boolean);a.manualEntries=(old.length?old:['Legend entry']).map(label=>ensureLegendEntry({id:uid(),label,visible:true}))}return a.manualEntries.map(ensureLegendEntry)}const curves=owner?.curves||[];a.entries=a.entries||[];curves.forEach(c=>{if(!a.entries.some(e=>e.curveId===c.id))a.entries.push({curveId:c.id,label:c.label,visible:true,color:'#111111',bold:false,italic:false})});return a.entries.filter(e=>curves.some(c=>c.id===e.curveId)).map(ensureLegendEntry)}
function legendLines(a,owner){return legendEntries(a,owner).filter(e=>e.visible!==false).map(e=>e.label)}
function legendOwner(a,owner){return owner||fig().panels.find(p=>p.id===a.sourcePanelId)||panel()}
function renderLegendEntriesEditor(sel=selectedAnnotationObj()){
  const list=$('#legendEntriesList'),manual=$('#legendManualField');
  if(!sel||sel.a.type!=='legend'){list.innerHTML='';manual.classList.add('hidden');return}
  const a=sel.a,owner=legendOwner(a,sel.owner),entries=legendEntries(a,owner);
  manual.classList.toggle('hidden',a.mode!=='manual');list.innerHTML='';
  entries.forEach(entry=>{
    const row=document.createElement('div'),check=document.createElement('input'),swatch=document.createElement('span'),name=document.createElement('input'),color=document.createElement('input'),bold=document.createElement('button'),italic=document.createElement('button'),sub=document.createElement('button'),sup=document.createElement('button');
    row.className='legendEntryRow';check.type='checkbox';check.checked=entry.visible!==false;check.title='Show or hide this legend entry';swatch.className='legendCurveSwatch';
    const c=owner?.curves.find(x=>x.id===entry.curveId);swatch.style.background=c?.color||'transparent';
    name.type='text';name.value=entry.label;name.title='Rename this legend entry';color.type='color';color.value=entry.color||'#111111';color.title='Legend text color';
    bold.type=italic.type=sub.type=sup.type='button';bold.className='toggleBtn'+(entry.bold?' active':'');italic.className='toggleBtn'+(entry.italic?' active':'');sub.className=sup.className='toggleBtn scriptBtn';bold.innerHTML='<b>B</b>';italic.innerHTML='<i>I</i>';sub.textContent='x₂';sup.textContent='x²';bold.title='Bold legend text';italic.title='Italic legend text';sub.title='Format selected characters as subscript';sup.title='Format selected characters as superscript';
    check.onchange=()=>{entry.visible=check.checked;render()};name.oninput=()=>{entry.label=name.value;render()};color.oninput=()=>{entry.color=color.value;render()};bold.onclick=()=>{entry.bold=!entry.bold;renderLegendEntriesEditor(sel);render()};italic.onclick=()=>{entry.italic=!entry.italic;renderLegendEntriesEditor(sel);render()};
    [sub,sup].forEach(button=>button.onpointerdown=e=>e.preventDefault());sub.onclick=()=>formatInputSelection(name,'sub',value=>{entry.label=value;render()});sup.onclick=()=>formatInputSelection(name,'sup',value=>{entry.label=value;render()});
    row.append(check,swatch,name,color,bold,italic,sub,sup);list.appendChild(row)
  })
}
function renderAnnotationList(){const sel=selectedAnnotationObj(),isLegend=sel?.a.type==='legend',isShape=sel?.a.type==='shape',drawing=!!state.drawingShape,showShape=isShape||drawing;$('#annotationCreate').classList.remove('hidden');$('#annotationEditor').classList.toggle('hidden',!sel||isLegend||isShape);$('#legendEditor').classList.toggle('hidden',!sel||!isLegend);$('#shapeEditor').classList.toggle('hidden',!showShape);$('#addVector').classList.toggle('drawing',drawing);$('#figureSvg').classList.toggle('drawingShape',drawing);if(!isLegend){$('#legendEntriesPopover').classList.add('hidden');$('#editLegendEntries').setAttribute('aria-expanded','false')}if(!sel){if(drawing){$('#shapeScopeBadge').textContent=`New ${shapeDefaults.scope} ${shapeDefaults.endCap==='arrow'?'arrow':'line'}`;$('#shapeScope').value=shapeDefaults.scope;$('#shapeColor').value=shapeDefaults.color;$('#shapeWidth').value=shapeDefaults.width;$('#shapeStyle').value=shapeDefaults.lineStyle;$('#shapeStartCap').value=shapeDefaults.startCap;$('#shapeEndCap').value=shapeDefaults.endCap}return}const a=sel.a,owner=sel.owner;if(isLegend){$('#legendScopeBadge').textContent=sel.scope==='panel'?`Panel ${fig().panels.indexOf(owner)+1} legend`:'Figure legend';$('#legendScope').value=sel.scope;$('#legendMode').value=a.mode||'auto';$('#legendSize').value=a.size||14;$('#legendBackground').classList.toggle('active',a.background!==false);$('#legendBackground').setAttribute('aria-pressed',String(a.background!==false));renderLegendEntriesEditor(sel);return}if(isShape){$('#shapeScopeBadge').textContent=sel.scope==='panel'?`Panel ${fig().panels.indexOf(owner)+1} ${a.endCap==='arrow'?'arrow':'line'}`:`Figure ${a.endCap==='arrow'?'arrow':'line'}`;$('#shapeScope').value=sel.scope;$('#shapeColor').value=a.color||'#111111';$('#shapeWidth').value=a.width||1.5;$('#shapeStyle').value=a.lineStyle||'solid';$('#shapeStartCap').value=a.startCap||'none';$('#shapeEndCap').value=a.endCap||'none';return}$('#annotationScopeBadge').textContent=sel.scope==='panel'?`Panel ${fig().panels.indexOf(owner)+1} text`:'Figure text';$('#annotationText').value=a.text;$('#annotationSize').value=a.size;$('#annotationRotation').value=String(a.rotation||0);$('#annotationColor').value=a.color||'#111111';$('#annotationBold').classList.toggle('active',!!a.bold);$('#annotationItalic').classList.toggle('active',!!a.italic)}
function curvePoints(c){const d=datasetById(c.datasetId);if(!d)return[];const out=[];d.rows.forEach(r=>{const x=Number(r[c.xIndex]),y=Number(r[c.yIndex]);if(Number.isFinite(x)&&Number.isFinite(y))out.push({x,y:y+(c.offset||0)})});return out}
function localRanges(p){let xs=[],ys=[];p.curves.filter(c=>c.visible!==false).forEach(c=>{curvePoints(c).forEach(q=>{xs.push(q.x);ys.push(q.y)})});if(!xs.length)return{x0:0,x1:1,y0:0,y1:1};let x0=Math.min(...xs),x1=Math.max(...xs),y0=Math.min(...ys),y1=Math.max(...ys),xSpan=x1-x0||Math.max(1,Math.abs(x1)*.01),ySpan=y1-y0||Math.max(1,Math.abs(y1)*.01);if(p.xScale==='manual'&&Number.isFinite(p.xMin)&&Number.isFinite(p.xMax)&&p.xMin!==p.xMax){x0=Math.min(p.xMin,p.xMax);x1=Math.max(p.xMin,p.xMax)}else if(p.xScale==='auto'){x0-=xSpan*.05;x1+=xSpan*.05}if(p.yScale==='manual'&&Number.isFinite(p.yMin)&&Number.isFinite(p.yMax)&&p.yMin!==p.yMax){y0=Math.min(p.yMin,p.yMax);y1=Math.max(p.yMin,p.yMax)}else if(p.yScale==='tight'){y0-=ySpan*.006;y1+=ySpan*.014}else{y0-=ySpan*.08;y1+=ySpan*.1}return{x0,x1,y0,y1}}
function axisPeers(p,axis){const mode=fig()[axis+'LinkMode']||'independent';if(mode==='all')return fig().panels;if(axis==='x'&&mode==='column'&&p.gridCol!==null)return fig().panels.filter(q=>q.gridCol===p.gridCol);if(axis==='y'&&mode==='row'&&p.gridRow!==null)return fig().panels.filter(q=>q.gridRow===p.gridRow);return[p]}
function panelHasVisibleData(p){return p.curves.some(c=>c.visible!==false&&curvePoints(c).length)}
function rangesFor(p){let r=localRanges(p),xPeers=axisPeers(p,'x').filter(panelHasVisibleData),yPeers=axisPeers(p,'y').filter(panelHasVisibleData);if(!xPeers.length)xPeers=[p];if(!yPeers.length)yPeers=[p];const xp=xPeers.map(localRanges),yp=yPeers.map(localRanges);r.x0=Math.min(...xp.map(x=>x.x0));r.x1=Math.max(...xp.map(x=>x.x1));r.y0=Math.min(...yp.map(x=>x.y0));r.y1=Math.max(...yp.map(x=>x.y1));return r}
function setSharedAxisValue(p,axis,key,value){axisPeers(p,axis).forEach(q=>q[key]=value)}
function pathFromPoints(points,sx,sy){return points.map((q,i)=>(i?'L':'M')+sx(q.x).toFixed(2)+' '+sy(q.y).toFixed(2)).join(' ')}
function lineDash(style){return style==='dash'?'7 5':style==='dot'?'2 4':''}
function fitCanvas(){const pane=$('#canvasPane'),wrap=$('.paperWrap'),f=fig();if(!pane||!wrap||state.dataMode)return;const scale=Math.max(.02,Math.min((pane.clientWidth-28)/f.width,(pane.clientHeight-28)/f.height));wrap.style.width=`${f.width*scale}px`;wrap.style.height=`${f.height*scale}px`}
function updateOffsetUI(p=panel()){if(!p)return;['x','y'].forEach(axis=>{const cap=axis.toUpperCase(),offset=p[axis==='x'?'xLabelOffsetY':'yLabelOffsetX']||0;$('#'+axis+'LabelOffsetValue').textContent=`${offset>0?'+':''}${Math.round(offset)} px`;$('#reset'+cap+'LabelOffset').disabled=Math.abs(offset)<.5})}
function render(){const svg=$('#figureSvg'),f=fig();svg.setAttribute('viewBox',`0 0 ${f.width} ${f.height}`);svg.style.aspectRatio=`${f.width}/${f.height}`;svg.innerHTML='';svg.appendChild(svgEl('rect',{x:0,y:0,width:f.width,height:f.height,fill:'#fff',class:'canvasBackground'}));f.panels.forEach((p,pi)=>renderPanel(svg,p,pi));f.panels.forEach(p=>p.annotations.filter(a=>a.type!=='shape').forEach(a=>renderAnnotation(svg,a,'panel',p)));f.annotations.filter(a=>a.type!=='shape').forEach(a=>renderAnnotation(svg,a,'figure',null));svg.querySelectorAll('.tickLabelGroup').forEach(g=>svg.appendChild(g));f.panels.forEach(p=>p.annotations.filter(a=>a.type==='shape').forEach(a=>renderShape(svg,a,'panel',p)));f.annotations.filter(a=>a.type==='shape').forEach(a=>renderShape(svg,a,'figure',null));(state.snapGuides||[]).forEach(g=>svg.appendChild(svgEl('line',{x1:g.x1,y1:g.y1,x2:g.x2,y2:g.y2,class:'snapGuide'})));bindCanvasInteractions();updateOffsetUI();requestAnimationFrame(fitCanvas)}
function renderPanel(svg,p,pi){const r=rangesFor(p),left=p.x,right=p.x+p.w,top=p.y,bottom=p.y+p.h,sx=x=>p.reverseX?right-(x-r.x0)/(r.x1-r.x0||1)*(right-left):left+(x-r.x0)/(r.x1-r.x0||1)*(right-left),sy=y=>p.reverseY?top+(y-r.y0)/(r.y1-r.y0||1)*(bottom-top):bottom-(y-r.y0)/(r.y1-r.y0||1)*(bottom-top);const clipId='clip_'+p.id,defs=svgEl('defs'),clip=svgEl('clipPath',{id:clipId});clip.appendChild(svgEl('rect',{x:left,y:top,width:right-left,height:bottom-top}));defs.appendChild(clip);svg.appendChild(defs);const g=svgEl('g',{'data-panel-id':p.id});
  p.curves.filter(c=>c.visible!==false).forEach(c=>{const pts=curvePoints(c);if(!pts.length)return;const cg=svgEl('g',{'clip-path':`url(#${clipId})`});if(c.fillMode!=='none'){let basePts=[];if(c.fillMode==='background'&&c.backgroundId){const bg=p.curves.find(q=>q.id===c.backgroundId),bp=bg?curvePoints(bg):[];if(bp.length===pts.length)basePts=bp}else if(c.fillMode==='axis')basePts=pts.map(q=>({x:q.x,y:r.y0}));if(basePts.length){const poly=[...pts,...basePts.slice().reverse()],d=poly.map((q,i)=>(i?'L':'M')+sx(q.x).toFixed(2)+' '+sy(q.y).toFixed(2)).join(' ')+' Z';cg.appendChild(svgEl('path',{d,fill:c.color,'fill-opacity':c.fillOpacity,stroke:'none'}))}}if(c.lineStyle!=='none'&&c.lineWidth>0)cg.appendChild(svgEl('path',{d:pathFromPoints(pts,sx,sy),fill:'none',stroke:c.color,'stroke-width':c.lineWidth,'stroke-dasharray':lineDash(c.lineStyle),'stroke-linejoin':'round','stroke-linecap':'round'}));if(c.markerStyle!=='none'){const step=Math.max(1,Math.floor(pts.length/220));for(let i=0;i<pts.length;i+=step){const q=pts[i],x=sx(q.x),y=sy(q.y),s=c.markerSize||3;if(c.markerStyle==='circle')cg.appendChild(svgEl('circle',{cx:x,cy:y,r:s/2,fill:c.markerColor}));else if(c.markerStyle==='square')cg.appendChild(svgEl('rect',{x:x-s/2,y:y-s/2,width:s,height:s,fill:c.markerColor}));else cg.appendChild(svgEl('path',{d:`M${x} ${y-s/1.4} L${x+s/1.4} ${y} L${x} ${y+s/1.4} L${x-s/1.4} ${y} Z`,fill:c.markerColor}))}}svg.appendChild(cg)});
  drawAxes(svg,p,r,left,right,top,bottom,sx,sy);const hit=svgEl('rect',{x:p.x,y:p.y,width:p.w,height:p.h,fill:'transparent',stroke:'transparent','stroke-width':1,class:'panelHit'+(p.locked?' locked':''),'data-panel-id':p.id});svg.appendChild(hit);if(p.id===state.selectedPanelId&&state.canvasSelection==='panel'){const sg=svgEl('g',{class:'panelSelectBadge'});sg.appendChild(svgEl('rect',{x:p.x-5,y:p.y-5,width:11,height:11,rx:2}));svg.appendChild(sg)}}
function drawAxes(svg,p,r,left,right,top,bottom,sx,sy){
  const sideCoords={
    top:[p.x,p.y,p.x+p.w,p.y],
    right:[p.x+p.w,p.y,p.x+p.w,p.y+p.h],
    bottom:[p.x,p.y+p.h,p.x+p.w,p.y+p.h],
    left:[p.x,p.y,p.x,p.y+p.h]
  };
  Object.entries(p.sides).forEach(([side,on])=>{
    if(on){
      const c=sideCoords[side];
      const axis=side==='top'||side==='bottom'?'x':'y';
      svg.appendChild(svgEl('line',{x1:c[0],y1:c[1],x2:c[2],y2:c[3],class:'axisLine',stroke:p[axis+'TickColor'],'stroke-width':p[axis+'TickWidth'],style:`stroke:${p[axis+'TickColor']};stroke-width:${p[axis+'TickWidth']}`}));
    }
  });
  const xt=ticksFor(p,'x',r.x0,r.x1);
  const xAttrs={class:'axisLine',stroke:p.xTickColor,'stroke-width':p.xTickWidth,style:`stroke:${p.xTickColor};stroke-width:${p.xTickWidth}`};
  if(p.xTicks){
    xt.forEach(v=>{
      const x=sx(v);
      if(p.sides.bottom)svg.appendChild(svgEl('line',{x1:x,y1:p.y+p.h,x2:x,y2:p.y+p.h-p.xTickLength,...xAttrs}));
      if(p.sides.top)svg.appendChild(svgEl('line',{x1:x,y1:p.y,x2:x,y2:p.y+p.xTickLength,...xAttrs}));
    });
    drawMinorTicks(svg,xt,p.xMinorTicks,sx,p.y,p.y+p.h,p.sides.top,p.sides.bottom,p.xMinorLength,xAttrs,'x');
  }
  if(p.xLabels&&p.sides.bottom){
    const selected=state.selectedTickLabels?.panelId===p.id&&state.selectedTickLabels.axis==='x',g=svgEl('g',{class:'tickLabelGroup xTickLabelGroup'+(selected?' selected':''),'data-panel-id':p.id,'data-tick-axis':'x'}),y=p.y+p.h+p.xTickLabelSize+6+p.xLabelOffsetY;
    if(selected)g.appendChild(svgEl('rect',{x:p.x-3,y:y-p.xTickLabelSize-4,width:p.w+6,height:p.xTickLabelSize+10,rx:3,class:'tickLabelSelection'}));
    xt.forEach(v=>g.appendChild(svgEl('text',{x:sx(v),y,'text-anchor':'middle',class:'axisText',fill:p.xTickLabelColor,'font-size':p.xTickLabelSize,'font-weight':p.xTickLabelBold?'700':'400','font-style':p.xTickLabelItalic?'italic':'normal',style:`fill:${p.xTickLabelColor};font-size:${p.xTickLabelSize}px;font-weight:${p.xTickLabelBold?'700':'400'};font-style:${p.xTickLabelItalic?'italic':'normal'}`},String(+v.toPrecision(6)))));svg.appendChild(g);
  }
  const yt=ticksFor(p,'y',r.y0,r.y1);
  const yAttrs={class:'axisLine',stroke:p.yTickColor,'stroke-width':p.yTickWidth,style:`stroke:${p.yTickColor};stroke-width:${p.yTickWidth}`};
  if(p.yTicks){
    yt.forEach(v=>{
      const y=sy(v);
      if(p.sides.left)svg.appendChild(svgEl('line',{x1:p.x,y1:y,x2:p.x+p.yTickLength,y2:y,...yAttrs}));
      if(p.sides.right)svg.appendChild(svgEl('line',{x1:p.x+p.w,y1:y,x2:p.x+p.w-p.yTickLength,y2:y,...yAttrs}));
    });
    drawMinorTicks(svg,yt,p.yMinorTicks,sy,p.x,p.x+p.w,p.sides.left,p.sides.right,p.yMinorLength,yAttrs,'y');
  }
  if(p.yLabels&&p.sides.left){
    const selected=state.selectedTickLabels?.panelId===p.id&&state.selectedTickLabels.axis==='y',g=svgEl('g',{class:'tickLabelGroup yTickLabelGroup'+(selected?' selected':''),'data-panel-id':p.id,'data-tick-axis':'y'}),x=p.x-7+p.yLabelOffsetX;
    if(selected)g.appendChild(svgEl('rect',{x:x-p.yTickLabelSize*4.4,y:p.y-3,width:p.yTickLabelSize*4.7,height:p.h+6,rx:3,class:'tickLabelSelection'}));
    yt.forEach(v=>g.appendChild(svgEl('text',{x,y:sy(v)+p.yTickLabelSize*.34,'text-anchor':'end',class:'axisText',fill:p.yTickLabelColor,'font-size':p.yTickLabelSize,'font-weight':p.yTickLabelBold?'700':'400','font-style':p.yTickLabelItalic?'italic':'normal',style:`fill:${p.yTickLabelColor};font-size:${p.yTickLabelSize}px;font-weight:${p.yTickLabelBold?'700':'400'};font-style:${p.yTickLabelItalic?'italic':'normal'}`},String(+v.toPrecision(5)))));svg.appendChild(g);
  }
}
function drawMinorTicks(svg,major,count,scale,start,end,firstSide,secondSide,length,attrs,axis){const n=Number(count)||0;if(!n||major.length<2)return;for(let i=0;i<major.length-1;i++){for(let j=1;j<=n;j++){const value=major[i]+(major[i+1]-major[i])*j/(n+1),pos=scale(value);if(axis==='x'){if(secondSide)svg.appendChild(svgEl('line',{x1:pos,y1:end,x2:pos,y2:end-length,...attrs}));if(firstSide)svg.appendChild(svgEl('line',{x1:pos,y1:start,x2:pos,y2:start+length,...attrs}))}else{if(firstSide)svg.appendChild(svgEl('line',{x1:start,y1:pos,x2:start+length,y2:pos,...attrs}));if(secondSide)svg.appendChild(svgEl('line',{x1:end,y1:pos,x2:end-length,y2:pos,...attrs}))}}}}
function renderAnnotation(svg,a,scope,p){if(a.type==='legend'){renderLegend(svg,a,scope,p);return}if(a.type==='shape'){renderShape(svg,a,scope,p);return}const x=scope==='panel'?p.x+a.x*p.w:a.x,y=scope==='panel'?p.y+a.y*p.h:a.y,rotation=Number(a.rotation)||0,color=a.color||'#111111',size=a.size||18,t=svgEl('text',{x,y,'font-size':size,fill:color,'font-weight':a.bold?'700':'400','font-style':a.italic?'italic':'normal',style:`fill:${color};font-size:${size}px;font-weight:${a.bold?'700':'400'};font-style:${a.italic?'italic':'normal'}`,transform:rotation?`rotate(${rotation} ${x} ${y})`:'',class:'annotationSvg'+(state.selectedAnnotation?.id===a.id?' selected':''),'data-ann-id':a.id,'data-ann-scope':scope,'data-panel-id':scope==='panel'?p.id:''},a.text);svg.appendChild(t)}
function renderShape(svg,a,scope,p){const x1=scope==='panel'?p.x+a.x*p.w:a.x,y1=scope==='panel'?p.y+a.y*p.h:a.y,x2=scope==='panel'?p.x+a.x2*p.w:a.x2,y2=scope==='panel'?p.y+a.y2*p.h:a.y2,color=a.color||'#111111',width=a.width||1.5,selected=state.selectedAnnotation?.id===a.id,markerId=`arrow_${a.id}`,defs=svgEl('defs'),marker=svgEl('marker',{id:markerId,viewBox:'0 0 8 8',refX:7,refY:4,markerWidth:6,markerHeight:6,orient:'auto-start-reverse',markerUnits:'strokeWidth'});marker.appendChild(svgEl('path',{d:'M 0 0 L 8 4 L 0 8 z',fill:color}));defs.appendChild(marker);svg.appendChild(defs);const g=svgEl('g',{class:'shapeSvg'+(selected?' selected':''),'data-ann-id':a.id,'data-ann-scope':scope,'data-panel-id':scope==='panel'?p.id:'',style:'cursor:move'}),attrs={x1,y1,x2,y2,stroke:color,'stroke-width':width,'stroke-dasharray':lineDash(a.lineStyle),'stroke-linecap':'round','marker-start':a.startCap==='arrow'?`url(#${markerId})`:'','marker-end':a.endCap==='arrow'?`url(#${markerId})`:''};g.appendChild(svgEl('line',{x1,y1,x2,y2,class:'shapeHit'}));g.appendChild(svgEl('line',attrs));if(selected){g.appendChild(svgEl('line',{x1,y1,x2,y2,class:'shapeSelection'}));g.appendChild(svgEl('circle',{cx:x1,cy:y1,r:5,class:'shapeHandle','data-shape-handle':'start'}));g.appendChild(svgEl('circle',{cx:x2,cy:y2,r:5,class:'shapeHandle','data-shape-handle':'end'}))}svg.appendChild(g)}
function renderLegend(svg,a,scope,p){
  const owner=legendOwner(a,scope==='panel'?p:null),x=scope==='panel'?p.x+a.x*p.w:a.x,y=scope==='panel'?p.y+a.y*p.h:a.y,size=a.size||14,items=legendEntries(a,owner).filter(e=>e.visible!==false),lines=items.map(e=>e.label),lh=size*1.35,width=Math.max(70,...lines.map(s=>String(s).length*size*.62))+32,height=Math.max(lh,lines.length*lh)+10;
  const g=svgEl('g',{class:'legendSvg'+(state.selectedAnnotation?.id===a.id?' selected':''),'data-ann-id':a.id,'data-ann-scope':scope,'data-panel-id':scope==='panel'?p.id:'',style:'cursor:move;pointer-events:all'});
  g.appendChild(svgEl('rect',{x:x-8,y:y-size-2,width:width+2,height:height+3,rx:3,class:'legendHit',fill:'transparent','pointer-events':'all'}));
  g.appendChild(svgEl('rect',{x:x-7,y:y-size,width,height,rx:3,class:'legendFrame',fill:'#fff','fill-opacity':a.background===false?0:.8,stroke:'none','pointer-events':'all',style:`fill:#fff;fill-opacity:${a.background===false?0:.8}`}));
  lines.forEach((label,i)=>{const yy=y+i*lh,entry=items[i];if(a.mode!=='manual'){const c=owner?.curves.find(q=>q.id===entry?.curveId);if(c){g.appendChild(svgEl('line',{x1:x,y1:yy-size*.28,x2:x+17,y2:yy-size*.28,stroke:c.color,'stroke-width':Math.max(1,c.lineWidth||1),'stroke-dasharray':lineDash(c.lineStyle),'pointer-events':'none'}));if(c.markerStyle!=='none')g.appendChild(svgEl('circle',{cx:x+8.5,cy:yy-size*.28,r:Math.max(1,(c.markerSize||3)/2),fill:c.markerColor||c.color,'pointer-events':'none'}))}}const textColor=entry.color||'#111111';g.appendChild(svgEl('text',{x:x+(a.mode==='manual'?0:24),y:yy,'font-size':size,class:'legendEntryText',fill:textColor,'font-weight':entry.bold?'700':'400','font-style':entry.italic?'italic':'normal',style:`font-size:${size}px;fill:${textColor};font-weight:${entry.bold?'700':'400'};font-style:${entry.italic?'italic':'normal'};pointer-events:none`},label))});
  svg.appendChild(g)
}
function snappedPanelPosition(p,x,y){const f=fig(),threshold=8,gx=f.gapX||0,gy=f.gapY||0;let sx=x,sy=y,bestX=threshold+1,bestY=threshold+1,guides=[];f.panels.filter(q=>q.id!==p.id).forEach(q=>{const xs=[{v:q.x,g:q.x},{v:q.x+q.w-p.w,g:q.x+q.w},{v:q.x+q.w+gx,g:q.x+q.w+gx},{v:q.x-p.w-gx,g:q.x-gx}],ys=[{v:q.y,g:q.y},{v:q.y+q.h-p.h,g:q.y+q.h},{v:q.y+q.h+gy,g:q.y+q.h+gy},{v:q.y-p.h-gy,g:q.y-gy}];xs.forEach(c=>{const d=Math.abs(x-c.v);if(d<bestX){bestX=d;sx=c.v;guides=guides.filter(g=>g.kind!=='x');guides.push({kind:'x',x1:c.g,y1:0,x2:c.g,y2:f.height})}});ys.forEach(c=>{const d=Math.abs(y-c.v);if(d<bestY){bestY=d;sy=c.v;guides=guides.filter(g=>g.kind!=='y');guides.push({kind:'y',x1:0,y1:c.g,x2:f.width,y2:c.g})}})});if(bestX>threshold)guides=guides.filter(g=>g.kind!=='x');if(bestY>threshold)guides=guides.filter(g=>g.kind!=='y');return{x:clamp(sx,0,f.width-p.w),y:clamp(sy,0,f.height-p.h),guides}}
function annotationAbs(a,scope,owner){return scope==='panel'?{x:owner.x+a.x*owner.w,y:owner.y+a.y*owner.h}:{x:a.x,y:a.y}}
function snappedAnnotationPosition(a,scope,owner,x,y,disabled){if(disabled)return{x,y,guides:[]};const f=fig(),threshold=8,targetsX=scope==='panel'?[owner.x,owner.x+owner.w/2,owner.x+owner.w]:[0,f.width/2,f.width],targetsY=scope==='panel'?[owner.y,owner.y+owner.h/2,owner.y+owner.h]:[0,f.height/2,f.height];[...f.annotations,...f.panels.flatMap(q=>q.annotations)].filter(o=>o.id!==a.id).forEach(o=>{let op=f.panels.find(q=>q.annotations.includes(o)),pos=annotationAbs(o,op?'panel':'figure',op);targetsX.push(pos.x);targetsY.push(pos.y)});let sx=x,sy=y,bx=threshold+1,by=threshold+1,guides=[];targetsX.forEach(v=>{const d=Math.abs(x-v);if(d<bx){bx=d;sx=v}});targetsY.forEach(v=>{const d=Math.abs(y-v);if(d<by){by=d;sy=v}});if(bx<=threshold)guides.push({kind:'x',x1:sx,y1:0,x2:sx,y2:f.height});if(by<=threshold)guides.push({kind:'y',x1:0,y1:sy,x2:f.width,y2:sy});return{x:sx,y:sy,guides}}
function bindCanvasInteractions(){
  const svg=$('#figureSvg');
  if(svg._shapePointerDown)svg.removeEventListener('pointerdown',svg._shapePointerDown,true);
  svg._shapePointerDown=e=>{if(!state.drawingShape)return;e.preventDefault();e.stopImmediatePropagation();const owner=panel(),scope=shapeDefaults.scope||'panel',start=svgPoint(e),local=scope==='panel'?{x:(start.x-owner.x)/owner.w,y:(start.y-owner.y)/owner.h}:start,a={id:uid(),type:'shape',x:local.x,y:local.y,x2:local.x,y2:local.y,color:shapeDefaults.color,width:shapeDefaults.width,lineStyle:shapeDefaults.lineStyle,startCap:shapeDefaults.startCap,endCap:shapeDefaults.endCap};if(scope==='panel')owner.annotations.push(a);else fig().annotations.push(a);state.selectedAnnotation={id:a.id,scope,panelId:scope==='panel'?owner.id:null};state.selectedTickLabels=null;state.canvasSelection='annotation';const origin={x:start.x,y:start.y};function move(ev){ev.preventDefault();let q=svgPoint(ev),dx=q.x-origin.x,dy=q.y-origin.y;if(ev.shiftKey){const len=Math.hypot(dx,dy),angle=Math.round(Math.atan2(dy,dx)/(Math.PI/4))*(Math.PI/4);q={x:origin.x+Math.cos(angle)*len,y:origin.y+Math.sin(angle)*len}}if(scope==='panel'){a.x2=(q.x-owner.x)/owner.w;a.y2=(q.y-owner.y)/owner.h}else{a.x2=q.x;a.y2=q.y}render()}function up(){window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);state.drawingShape=null;const length=scope==='panel'?Math.hypot((a.x2-a.x)*owner.w,(a.y2-a.y)*owner.h):Math.hypot(a.x2-a.x,a.y2-a.y);if(length<3){if(scope==='panel')a.x2=a.x+.12;else a.x2=a.x+80;a.y2=a.y}renderAnnotationList();render();scheduleHistoryCommit()}window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);renderAnnotationList();render()};
  svg.addEventListener('pointerdown',svg._shapePointerDown,true);
  $('.canvasBackground').onpointerdown=e=>{if(state.drawingShape||e.target!==$('.canvasBackground'))return;state.selectedAnnotation=null;state.selectedTickLabels=null;state.canvasSelection=null;renderAnnotationList();render()};
  $$('.panelHit').forEach(hit=>{
    hit.onpointerdown=e=>{
      if(state.drawingShape)return;const p=fig().panels.find(x=>x.id===hit.dataset.panelId);if(!p)return;
      const start=svgPoint(e),ox=p.x,oy=p.y;
      state.selectedPanelId=p.id;state.selectedCurveId=p.curves[0]?.id||null;state.selectedAnnotation=null;state.selectedTickLabels=null;state.canvasSelection='panel';state.panelDatasetPanelId=null;syncUI();
      let dragging=false;
      function move(ev){
        if(p.locked)return;
        const q=svgPoint(ev),dx=q.x-start.x,dy=q.y-start.y;
        if(!dragging&&Math.hypot(dx,dy)<7)return;
        dragging=true;const snap=snappedPanelPosition(p,ox+dx,oy+dy);p.x=snap.x;p.y=snap.y;state.snapGuides=snap.guides;syncGeomOnly();render();
      }
      function up(){window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);state.snapGuides=[];render()}
      window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)
    }
  });
  $$('.tickLabelGroup').forEach(group=>{
    group.onpointerdown=e=>{
      if(state.drawingShape)return;e.preventDefault();e.stopPropagation();const p=fig().panels.find(x=>x.id===group.dataset.panelId),axis=group.dataset.tickAxis;if(!p)return;
      state.selectedPanelId=p.id;state.selectedAnnotation=null;state.selectedTickLabels={panelId:p.id,axis};state.canvasSelection='ticks';const start=svgPoint(e),key=axis==='x'?'xLabelOffsetY':'yLabelOffsetX',original=p[key]||0;
      function move(ev){ev.preventDefault();const q=svgPoint(ev);p[key]=original+(axis==='x'?q.y-start.y:q.x-start.x);render()}
      function up(){window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);syncUI();render()}
      window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);syncUI();render()
    }
  });
  $$('.shapeHandle').forEach(handle=>{
    handle.onpointerdown=e=>{if(state.drawingShape)return;e.preventDefault();e.stopPropagation();const g=handle.closest('.shapeSvg'),scope=g.dataset.annScope,id=g.dataset.annId,pid=g.dataset.panelId,owner=scope==='panel'?fig().panels.find(x=>x.id===pid):null,src=scope==='panel'?owner?.annotations:fig().annotations,a=src?.find(x=>x.id===id);if(!a)return;state.selectedPanelId=owner?.id||state.selectedPanelId;state.selectedAnnotation={id,scope,panelId:scope==='panel'?pid:null};state.canvasSelection='annotation';const movingEnd=handle.dataset.shapeHandle==='end',fixed=scope==='panel'?{x:owner.x+(movingEnd?a.x:a.x2)*owner.w,y:owner.y+(movingEnd?a.y:a.y2)*owner.h}:{x:movingEnd?a.x:a.x2,y:movingEnd?a.y:a.y2};function move(ev){ev.preventDefault();let q=svgPoint(ev),dx=q.x-fixed.x,dy=q.y-fixed.y;if(ev.shiftKey){const len=Math.hypot(dx,dy),angle=Math.round(Math.atan2(dy,dx)/(Math.PI/4))*(Math.PI/4);q={x:fixed.x+Math.cos(angle)*len,y:fixed.y+Math.sin(angle)*len}}const snap=snappedAnnotationPosition(a,scope,owner,q.x,q.y,ev.altKey);state.snapGuides=snap.guides;if(scope==='panel'){const nx=(snap.x-owner.x)/owner.w,ny=(snap.y-owner.y)/owner.h;if(movingEnd){a.x2=nx;a.y2=ny}else{a.x=nx;a.y=ny}}else if(movingEnd){a.x2=snap.x;a.y2=snap.y}else{a.x=snap.x;a.y=snap.y}render()}function up(){window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);state.snapGuides=[];renderAnnotationList();render()}window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);renderAnnotationList();render()}
  });
  $$('.annotationSvg,.legendSvg,.shapeSvg').forEach(t=>{
    t.onpointerdown=e=>{
      if(state.drawingShape)return;e.preventDefault();e.stopPropagation();
      const scope=t.dataset.annScope,id=t.dataset.annId,pid=t.dataset.panelId;
      if(scope==='panel'&&pid)state.selectedPanelId=pid;
      state.selectedAnnotation={id,scope,panelId:scope==='panel'?pid:null};state.selectedTickLabels=null;state.canvasSelection='annotation';
      const owner=scope==='panel'?fig().panels.find(x=>x.id===pid):null,src=scope==='panel'?owner?.annotations:fig().annotations,a=src?.find(x=>x.id===id);if(!a)return;
      const start=svgPoint(e),ox=a.x,oy=a.y,ox2=a.x2,oy2=a.y2;
      function move(ev){ev.preventDefault();const q=svgPoint(ev),base=scope==='panel'?{x:owner.x+(ox+(q.x-start.x)/owner.w)*owner.w,y:owner.y+(oy+(q.y-start.y)/owner.h)*owner.h}:{x:ox+q.x-start.x,y:oy+q.y-start.y},snap=snappedAnnotationPosition(a,scope,owner,base.x,base.y,ev.altKey);state.snapGuides=snap.guides;if(scope==='panel'){a.x=clamp((snap.x-owner.x)/owner.w,-.25,1.25);a.y=clamp((snap.y-owner.y)/owner.h,-.25,1.25);if(a.type==='shape'){a.x2=ox2+(a.x-ox);a.y2=oy2+(a.y-oy)}}else{a.x=snap.x;a.y=snap.y;if(a.type==='shape'){a.x2=ox2+(a.x-ox);a.y2=oy2+(a.y-oy)}}render()}
      function up(){window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);state.snapGuides=[];renderAnnotationList();syncUI();render()}
      window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);renderAnnotationList();render()
    }
  })
}
function svgPoint(e){const svg=$('#figureSvg'),pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;return pt.matrixTransform(svg.getScreenCTM().inverse())}
function syncGeomOnly(){const p=panel();if(!p)return;[['panelX','x','x'],['panelY','y','y'],['panelW','w','w'],['panelH','h','h']].forEach(([id,key,axis])=>{$('#'+id).value=displayGeom(p[key],axis)})}
function addAnnotation(scope){state.drawingShape=null;const a={id:uid(),type:'text',text:scope==='panel'?'4.5 V':'Figure title',size:20,color:'#111111',bold:false,italic:false,rotation:0};const owner=panel();if(scope==='panel'){a.x=.08;a.y=.1;owner.annotations.push(a)}else{a.x=38;a.y=32;fig().annotations.push(a)}state.selectedAnnotation={id:a.id,scope,panelId:scope==='panel'?owner.id:null};state.selectedTickLabels=null;state.canvasSelection='annotation';renderAnnotationList();render()}
function addLegend(){state.drawingShape=null;const owner=panel(),a={id:uid(),type:'legend',mode:'auto',size:14,x:.08,y:.15,background:true,sourcePanelId:owner.id,entries:owner.curves.map(c=>({curveId:c.id,label:c.label,visible:true})),text:''};owner.annotations.push(a);state.selectedAnnotation={id:a.id,scope:'panel',panelId:owner.id};state.selectedTickLabels=null;state.canvasSelection='annotation';renderAnnotationList();render()}
function startShapeTool(kind){state.drawingShape=state.drawingShape===kind?null:kind;state.selectedAnnotation=null;state.selectedTickLabels=null;state.canvasSelection=null;renderAnnotationList();render()}
function setShapeSetting(key,value){const s=selectedAnnotationObj();if(s?.a.type==='shape'){s.a[key]=value;render()}else if(state.drawingShape){shapeDefaults[key]=value;renderAnnotationList()}}
function copySelectedAnnotation(){const s=selectedAnnotationObj();if(!s)return false;annotationClipboard={annotation:structuredClone(s.a),scope:s.scope,figureId:fig().id};navigator.clipboard?.writeText(s.a.text||'').catch(()=>{});return true}
function pasteCopiedAnnotation(){if(!annotationClipboard||annotationClipboard.figureId!==fig().id)return false;const a=structuredClone(annotationClipboard.annotation);a.id=uid();const scope=annotationClipboard.scope;if(scope==='panel'){const owner=panel();if(!owner)return false;const dx=12/Math.max(1,owner.w),dy=12/Math.max(1,owner.h);a.x+=dx;a.y+=dy;if(a.type==='shape'){a.x2+=dx;a.y2+=dy}owner.annotations.push(a);state.panelDatasetPanelId=null;state.selectedAnnotation={id:a.id,scope,panelId:owner.id}}else{a.x+=12;a.y+=12;if(a.type==='shape'){a.x2+=12;a.y2+=12}fig().annotations.push(a);state.selectedAnnotation={id:a.id,scope,panelId:null}}annotationClipboard.annotation=structuredClone(a);state.selectedTickLabels=null;state.canvasSelection='annotation';syncUI();render();return true}
async function addDemo(){
  const hasWork=state.datasets.length>0||state.figures.length>1||state.figures.some(f=>f.annotations.length||f.panels.some(p=>p.curves.length||p.annotations.length));
  if(hasWork&&!confirm('Load the complete demo and replace the current project?'))return;
  try{
    const response=await fetch('./demo-project.json',{cache:'no-store'});
    if(!response.ok)throw new Error(`Demo file unavailable (${response.status})`);
    const demo=await response.json();
    if(demo.kind!=='xpsfig-project'||!demo.state)throw new Error('Invalid Figure Builder demo file.');
    applyProjectState(demo.state);showDataMode(false);resetProjectHistory();scheduleAutosave(projectSnapshot(),true,0)
  }catch(error){alert(`The demo could not be loaded. ${error.message}`)}
}
function renderDataTable(){
  const wrap=$('#dataTableWrap'),d=editorDataset();
  if(!d){wrap.innerHTML='<div class="microText">No data loaded.</div>';return}
  const max=500;let html='<div class="dataTableInner"><table class="dataTable"><thead><tr>'+d.headers.map((h,i)=>`<th><input data-header="${i}" value="${esc(h)}"><button data-delcol="${i}" title="Delete column">×</button></th>`).join('')+'</tr></thead><tbody>';
  d.rows.slice(0,max).forEach((r,ri)=>{html+='<tr>'+r.map((v,ci)=>`<td contenteditable="true" data-row="${ri}" data-col="${ci}" title="${esc(v)}">${esc(v)}</td>`).join('')+'</tr>'});html+='</tbody></table><span class="dataTableEndSpace" aria-hidden="true"></span></div>';
  if(d.rows.length>max)html+=`<div class="microText" style="margin-top:8px">Showing first ${max} of ${d.rows.length} rows.</div>`;
  wrap.innerHTML=html;
  $$('[data-header]').forEach(inp=>inp.onchange=()=>{const i=Number(inp.dataset.header),old=d.headers[i];d.headers[i]=inp.value.trim()||old;state.figures.forEach(f=>f.panels.forEach(p=>p.curves.forEach(c=>{if(c.datasetId===d.id&&c.yIndex===i&&c.label===old)c.label=d.headers[i]})));updateDataUI();renderCurveList();render()});
  $$('[data-delcol]').forEach(btn=>btn.onclick=()=>deleteColumn(d,Number(btn.dataset.delcol)));
  $$('.dataTable td[contenteditable]').forEach(td=>td.onblur=()=>{const r=Number(td.dataset.row),c=Number(td.dataset.col),raw=td.textContent.trim(),n=numericValue(raw);d.rows[r][c]=n===null?raw:n;render()})
}
function newEmptyDataset(){const d={id:uid(),name:`Data ${state.datasets.length+1}`,sourceFile:'Pasted data',headers:['X','Y'],rows:Array.from({length:30},()=>['','']),delimiter:'\t'};state.datasets.push(d);state.editorDatasetId=d.id;if(!currentDataset())setPanelDataset(d.id);updateDataUI();showDataMode(true);renderDataTable();setTimeout(()=>$('#dataTableWrap td')?.focus(),0)}
function pasteIntoTable(e){const d=editorDataset(),target=e.target.closest('td[data-row]');if(!d||!target)return;const text=e.clipboardData?.getData('text/plain');if(!text)return;const lines=text.replace(/\r/g,'').split('\n').filter((line,i,a)=>line.length||i<a.length-1),matrix=lines.map(line=>line.split('\t'));if(!matrix.length)return;e.preventDefault();const row0=Number(target.dataset.row),col0=Number(target.dataset.col),headerPaste=row0===0&&matrix.length>1&&matrix[0].filter(v=>numericValue(v)===null).length>matrix[0].length/2&&matrix[1].filter(v=>numericValue(v)!==null).length>=matrix[1].length/2,data=headerPaste?matrix.slice(1):matrix,neededCols=col0+Math.max(...matrix.map(r=>r.length));while(d.headers.length<neededCols)d.headers.push(`Column ${d.headers.length+1}`);if(headerPaste)matrix[0].forEach((value,ci)=>{if(value.trim())d.headers[col0+ci]=value.trim()});while(d.rows.length<row0+data.length)d.rows.push(Array(d.headers.length).fill(''));d.rows.forEach(r=>{while(r.length<d.headers.length)r.push('')});data.forEach((row,ri)=>row.forEach((value,ci)=>{const n=numericValue(value);d.rows[row0+ri][col0+ci]=n===null?value:n}));updateDataUI();renderDataTable();render()}
function deleteColumn(d,idx){if(d.headers.length<=2){alert('Keep at least two columns.');return}const affected=[];state.figures.forEach(f=>f.panels.forEach(p=>{p.curves=p.curves.filter(c=>{if(c.datasetId!==d.id)return true;if(c.xIndex===idx||c.yIndex===idx){affected.push(c.label);return false}if(c.xIndex>idx)c.xIndex--;if(c.yIndex>idx)c.yIndex--;return true})}));d.headers.splice(idx,1);d.rows.forEach(r=>r.splice(idx,1));state.selectedCurveId=null;updateDataUI();renderDataTable();syncUI();render();if(affected.length)alert(`Removed ${affected.length} curve${affected.length>1?'s':''} using the deleted column.`)}
function showDataMode(on){state.dataMode=on;$('#canvasPane').classList.toggle('hidden',on);$('#dataPane').classList.toggle('hidden',!on);$('.fbStage').classList.toggle('dataModeActive',on);$('#viewData').classList.toggle('active',on);$('#viewFigure').classList.toggle('active',!on);$('#dataContext').classList.toggle('hidden',!on);$('#figureContext').classList.toggle('hidden',on);if(on)renderDataTable();else requestAnimationFrame(fitCanvas)}
function saveProject(){commitHistory();const payload={kind:'xpsfig-project',version:2,savedAt:new Date().toISOString(),state};downloadBlob(new Blob([JSON.stringify(payload)],{type:'application/json'}),(fig().name||'XPS_figure')+'.xpsfig-project.json');markProjectSaved()}
function saveTemplate(){const f=structuredClone(fig());f.panels.forEach(p=>{p.curves=[];p.annotations=[]});f.annotations=[];downloadBlob(new Blob([JSON.stringify({kind:'xpsfig-template',version:2,figure:f})],{type:'application/json'}),(f.name||'XPS_figure')+'.xpsfig-template.json')}
function loadJsonFile(file,kind){const fr=new FileReader();fr.onload=()=>{try{const o=JSON.parse(fr.result);if(kind==='project'){if(o.kind!=='xpsfig-project'||!o.state)throw new Error('Not an XPS Figure Builder project.');applyProjectState(o.state);resetProjectHistory();scheduleAutosave(projectSnapshot(),false,0)}else{if(o.kind!=='xpsfig-template'||!o.figure)throw new Error('Not an XPS Figure Builder template.');const nf=structuredClone(o.figure),name=fig().name,id=fig().id;nf.name=name;nf.id=id;nf.panels.forEach(p=>{p.id=uid();p.curves=[];p.annotations=[];ensurePanel(p)});nf.annotations=[];state.figures[state.activeFigure]=nf;state.selectedPanelId=nf.panels[0]?.id||null;state.selectedCurveId=null;syncUI();render();commitHistory()}}catch(e){alert(e.message)}};fr.readAsText(file)}
async function initializeAutosave(){try{const draft=await readAutosaveDraft();autosaveReady=true;if(draft?.dirty&&draft.payload?.state){const when=autosaveTime(draft.savedAt),recover=confirm(`Recover the unsaved Figure Builder project from ${when||'the previous session'}?`);if(recover){applyProjectState(draft.payload.state);resetProjectHistory();lastAutosavedSnapshot=projectSnapshot();lastAutosaveDirty=true;setAutosaveStatus(`Recovered · ${when}`);return}await deleteAutosaveDraft()}else if(draft?.payload?.state){lastAutosavedSnapshot=JSON.stringify(draft.payload.state);lastAutosaveDirty=false}setAutosaveStatus('Autosave ready')}catch{autosaveReady=false;setAutosaveStatus('Autosave unavailable',true)}}
function cleanSvgClone(){const clone=$('#figureSvg').cloneNode(true),f=fig();clone.querySelectorAll('.panelHit,.panelSelectBadge,.tickLabelSelection,.legendHit,.shapeHit,.shapeHandle,.shapeSelection').forEach(n=>n.remove());clone.querySelectorAll('.annotationSvg.selected,.legendSvg.selected,.shapeSvg.selected,.tickLabelGroup.selected').forEach(n=>n.classList.remove('selected'));clone.setAttribute('viewBox',`0 0 ${f.width} ${f.height}`);clone.setAttribute('width',f.width);clone.setAttribute('height',f.height);return clone}
function exportSvg(){const clone=cleanSvgClone();downloadBlob(new Blob(['<?xml version="1.0" encoding="UTF-8"?>\n'+new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'}),(fig().name||'XPS_figure')+'.svg')}
function exportPng(){const clone=cleanSvgClone(),f=fig(),blob=new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const scale=2,cv=document.createElement('canvas');cv.width=Math.ceil(f.width*scale);cv.height=Math.ceil(f.height*scale);const ctx=cv.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,cv.width,cv.height);ctx.drawImage(img,0,0,cv.width,cv.height);URL.revokeObjectURL(url);cv.toBlob(out=>downloadBlob(out,(fig().name||'XPS_figure')+'.png'),'image/png')};img.src=url}

// Data
$('#csvFiles').addEventListener('change',async e=>{let last=null;for(const file of e.target.files){try{last=parseCSV(await file.text(),file.name);state.datasets.push(last)}catch(err){alert(`${file.name}: ${err.message}`)}}e.target.value='';if(last)state.editorDatasetId=last.id;updateDataUI();if(last){setPanelDataset(last.id);state.panelDatasetPanelId=panel()?.id||null;commitHistory()}});
$('#datasetSelect').onchange=e=>{setPanelDataset(e.target.value);state.panelDatasetPanelId=panel()?.id||null};$('#topDatasetSelect').onchange=e=>{state.editorDatasetId=e.target.value;renderDataTable()};
$('#xSelect').onchange=renderYMenu;
$('#yMultiButton').onclick=e=>{e.stopPropagation();$('#yMultiMenu').classList.toggle('hidden')};
document.addEventListener('click',e=>{if(!e.target.closest('#yMulti'))$('#yMultiMenu').classList.add('hidden')});
$('#addCurve').onclick=applySelectedY;$('#deleteDatasetTop').onclick=removeSelectedDataset;$('#newDataset').onclick=newEmptyDataset;$('#renameDataset').onclick=()=>{const d=editorDataset();if(!d)return;const n=prompt('Dataset name:',d.name);if(n){d.name=n.trim()||d.name;updateDataUI();renderDataTable()}};$('#dataTableWrap').addEventListener('paste',pasteIntoTable);$('#viewData').onclick=()=>showDataMode(true);$('#viewFigure').onclick=()=>showDataMode(false);$('#demoData').onclick=addDemo;
// Layout
$('#applyCanvas').onclick=()=>{const f=fig(),oldW=f.width,oldH=f.height,w=clamp(Number($('#canvasW').value)||oldW,200,6000),h=clamp(Number($('#canvasH').value)||oldH,150,6000),sx=w/oldW,sy=h/oldH;f.panels.forEach(p=>{p.x*=sx;p.w*=sx;p.y*=sy;p.h*=sy});f.annotations.forEach(a=>{a.x*=sx;a.y*=sy});f.gapX*=sx;f.gapY*=sy;f.width=w;f.height=h;syncUI();render()};
$('#applyGrid').onclick=applyGrid;
$('#addPanel').onclick=()=>{const f=fig(),p=defaultPanel(f.width*.1+f.panels.length*16,f.height*.08+f.panels.length*12,f.width*.42,f.height*.4);p.gridRow=null;p.gridCol=null;f.panels.push(p);state.selectedPanelId=p.id;state.selectedCurveId=null;state.selectedAnnotation=null;state.selectedTickLabels=null;state.canvasSelection='panel';syncUI();render()};
$('#dupPanel').onclick=()=>{const p=panel();if(!p)return;const n=structuredClone(p),curveMap=new Map(),oldPanelId=n.id;n.id=uid();n.x=clamp(n.x+24,0,fig().width-n.w);n.y=clamp(n.y+20,0,fig().height-n.h);n.curves=n.curves.map(c=>{const old=c.id,id=uid();curveMap.set(old,id);return{...c,id}});n.curves.forEach(c=>{if(c.backgroundId&&curveMap.has(c.backgroundId))c.backgroundId=curveMap.get(c.backgroundId)});n.annotations=n.annotations.map(a=>({...a,id:uid(),sourcePanelId:a.sourcePanelId===oldPanelId?n.id:a.sourcePanelId,entries:(a.entries||[]).map(e=>({...e,curveId:curveMap.get(e.curveId)||e.curveId}))}));fig().panels.push(n);state.selectedPanelId=n.id;state.selectedCurveId=n.curves[0]?.id||null;state.selectedAnnotation=null;state.selectedTickLabels=null;state.canvasSelection='panel';syncUI();render()};
function removeSelectedPanel(){if(fig().panels.length<=1)return;fig().panels=fig().panels.filter(p=>p.id!==state.selectedPanelId);state.selectedPanelId=fig().panels[0]?.id||null;state.selectedCurveId=null;state.selectedAnnotation=null;state.selectedTickLabels=null;state.canvasSelection='panel';syncUI();render()}
$('#removePanel').onclick=removeSelectedPanel;
$$('[data-unit]').forEach(b=>b.onclick=()=>{state.geomUnit=b.dataset.unit;syncUI()});
function commitGeomInput(id,key,axis){const input=$('#'+id),p=panel();if(!p||p.locked)return;const v=fromDisplay(input.value,axis);if(v===null){syncGeomOnly();return}if(key==='x')p.x=clamp(v,0,fig().width-p.w);else if(key==='y')p.y=clamp(v,0,fig().height-p.h);else if(key==='w')p.w=clamp(v,80,fig().width-p.x);else p.h=clamp(v,70,fig().height-p.y);syncGeomOnly();render()}
[['panelX','x','x'],['panelY','y','y'],['panelW','w','w'],['panelH','h','h']].forEach(([id,key,axis])=>{const el=$('#'+id);el.onblur=()=>commitGeomInput(id,key,axis);el.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();el.blur()}}});
$('#applyPanelGeometry').onclick=()=>{const p=panel(),f=fig();if(!p||p.locked)return;const x=fromDisplay($('#panelX').value,'x'),y=fromDisplay($('#panelY').value,'y'),w=fromDisplay($('#panelW').value,'w'),h=fromDisplay($('#panelH').value,'h');if([x,y,w,h].some(v=>v===null)){syncGeomOnly();return}p.w=clamp(w,80,f.width);p.h=clamp(h,70,f.height);p.x=clamp(x,0,f.width-p.w);p.y=clamp(y,0,f.height-p.h);syncGeomOnly();render()};
function syncAxisGroup(axis){const p=panel(),keys=['Scale','Min','Max','TickMode','TickCount','TickStep','TickFirst','MinorTicks'];axisPeers(p,axis).forEach(q=>{keys.forEach(k=>q[axis+k]=p[axis+k]);q[axis==='x'?'reverseX':'reverseY']=p[axis==='x'?'reverseX':'reverseY']})}
$('#xAxisMode').onchange=e=>{fig().xLinkMode=e.target.value;syncAxisGroup('x');syncUI();render()};$('#yAxisMode').onchange=e=>{fig().yLinkMode=e.target.value;syncAxisGroup('y');syncUI();render()};$('#reverseX').onchange=e=>{setSharedAxisValue(panel(),'x','reverseX',e.target.checked);render()};$('#reverseY').onchange=e=>{setSharedAxisValue(panel(),'y','reverseY',e.target.checked);render()};$('#lockPanel').onchange=e=>{panel().locked=e.target.checked;render()};
[['borderTop','top'],['borderRight','right'],['borderBottom','bottom'],['borderLeft','left']].forEach(([id,s])=>$('#'+id).onclick=()=>{panel().sides[s]=!panel().sides[s];syncUI();render()});
[['xTicks','xTicks'],['xLabels','xLabels'],['yTicks','yTicks'],['yLabels','yLabels']].forEach(([id,k])=>$('#'+id).onchange=e=>{panel()[k]=e.target.checked;render()});
['x','y'].forEach(axis=>{
  $$(`[data-${axis}scale]`).forEach(b=>b.onclick=()=>{const mode=b.dataset[axis+'scale'];if(mode==='manual'){const r=rangesFor(panel()),span=r[axis+'1']-r[axis+'0'],min=cleanManualLimit(r[axis+'0'],axis,span),max=cleanManualLimit(r[axis+'1'],axis,span);setSharedAxisValue(panel(),axis,axis+'Min',min);setSharedAxisValue(panel(),axis,axis+'Max',max)}setSharedAxisValue(panel(),axis,axis+'Scale',mode);syncUI();render()});
  $('#'+axis+'Min').oninput=e=>{setSharedAxisValue(panel(),axis,axis+'Min',e.target.value===''?null:Number(e.target.value));render()};$('#'+axis+'Max').oninput=e=>{setSharedAxisValue(panel(),axis,axis+'Max',e.target.value===''?null:Number(e.target.value));render()};
  $('#'+axis+'TickMode').onchange=e=>{setSharedAxisValue(panel(),axis,axis+'TickMode',e.target.value);syncUI();render()};
  $('#'+axis+'TickCount').oninput=e=>{setSharedAxisValue(panel(),axis,axis+'TickCount',Math.max(2,Number(e.target.value)||2));render()};$('#'+axis+'MinorTicks').onchange=e=>{setSharedAxisValue(panel(),axis,axis+'MinorTicks',Number(e.target.value)||0);render()};
  $('#'+axis+'TickStep').oninput=e=>{setSharedAxisValue(panel(),axis,axis+'TickStep',Math.abs(Number(e.target.value))||null);render()};$('#'+axis+'TickFirst').oninput=e=>{setSharedAxisValue(panel(),axis,axis+'TickFirst',e.target.value===''?null:Number(e.target.value));render()};
  [[axis+'TickLength',0],[axis+'MinorLength',0],[axis+'TickWidth',.25],[axis+'TickLabelSize',4]].forEach(([key,min])=>$('#'+key).oninput=e=>{panel()[key]=Math.max(min,Number(e.target.value)||min);render()});
  $('#'+axis+'TickColor').oninput=e=>{panel()[axis+'TickColor']=e.target.value;render()};$('#'+axis+'TickLabelColor').oninput=e=>{panel()[axis+'TickLabelColor']=e.target.value;render()};$('#'+axis+'TickLabelBold').onclick=()=>{panel()[axis+'TickLabelBold']=!panel()[axis+'TickLabelBold'];syncUI();render()};$('#'+axis+'TickLabelItalic').onclick=()=>{panel()[axis+'TickLabelItalic']=!panel()[axis+'TickLabelItalic'];syncUI();render()};
  $('#'+axis+'TickMore').onclick=e=>{const box=$('#'+axis+'TickAdvanced'),open=box.classList.toggle('hidden')===false;e.currentTarget.setAttribute('aria-expanded',String(open))};$('#reset'+axis.toUpperCase()+'LabelOffset').onclick=()=>{panel()[axis==='x'?'xLabelOffsetY':'yLabelOffsetX']=0;render()}
});
// Curves
$('#curveName').oninput=e=>{if(curve()){curve().label=e.target.value;renderCurveList()}};$('#curveRole').onchange=e=>{const c=curve();if(!c)return;c.role=e.target.value;if(c.role==='component'&&c.fillMode==='none')c.fillMode='background';renderCurveList();render()};$('#lineStyle').onchange=e=>{curve().lineStyle=e.target.value;render()};$('#lineWidth').oninput=e=>{curve().lineWidth=Number(e.target.value)||0;render()};$('#curveColor').oninput=e=>{curve().color=e.target.value;renderCurveList();render()};$('#markerStyle').onchange=e=>{curve().markerStyle=e.target.value;render()};$('#markerSize').oninput=e=>{curve().markerSize=Number(e.target.value)||1;render()};$('#markerColor').oninput=e=>{curve().markerColor=e.target.value;render()};$('#fillMode').onchange=e=>{const c=curve();c.fillMode=e.target.value;const bg=panel().curves.find(x=>x.role==='background'&&x.id!==c.id);if(c.fillMode==='background'&&!c.backgroundId&&bg)c.backgroundId=bg.id;renderCurveList();render()};$('#fillOpacity').oninput=e=>{curve().fillOpacity=clamp((Number(e.target.value)||0)/100,0,1);render()};$('#backgroundSelect').onchange=e=>{curve().backgroundId=e.target.value;render()};$('#stackPlus').onclick=()=>{const inc=Number($('#stackIncrement').value)||0;state.stackLevel++;panel().curves.forEach((c,i)=>c.offset=i*inc*state.stackLevel);render()};$('#stackReset').onclick=()=>{state.stackLevel=0;panel().curves.forEach(c=>c.offset=0);render()};
// Annotations
$('#addPanelText').onclick=()=>addAnnotation('panel');$('#addFigureText').onclick=()=>addAnnotation('figure');$('#addLegend').onclick=addLegend;$('#addVector').onclick=()=>startShapeTool('arrow');$('#annotationText').oninput=e=>{const s=selectedAnnotationObj();if(s){s.a.text=e.target.value;render()}};$('#annotationSize').oninput=e=>{const s=selectedAnnotationObj();if(s){s.a.size=Number(e.target.value)||18;render()}};$('#annotationRotation').onchange=e=>{const s=selectedAnnotationObj();if(s){s.a.rotation=Number(e.target.value)||0;render()}};$('#annotationColor').oninput=e=>{const s=selectedAnnotationObj();if(s){s.a.color=e.target.value;render()}};$('#annotationBold').onclick=()=>{const s=selectedAnnotationObj();if(s){s.a.bold=!s.a.bold;renderAnnotationList();render()}};$('#annotationItalic').onclick=()=>{const s=selectedAnnotationObj();if(s){s.a.italic=!s.a.italic;renderAnnotationList();render()}};
['annotationSubscript','annotationSuperscript'].forEach(id=>$('#'+id).onpointerdown=e=>e.preventDefault());
$('#annotationSubscript').onclick=()=>{const s=selectedAnnotationObj();if(s?.a.type==='text')formatInputSelection($('#annotationText'),'sub',value=>{s.a.text=value;render()})};
$('#annotationSuperscript').onclick=()=>{const s=selectedAnnotationObj();if(s?.a.type==='text')formatInputSelection($('#annotationText'),'sup',value=>{s.a.text=value;render()})};
function removeSelectedObject(){const s=selectedAnnotationObj();if(!s)return;if(s.scope==='panel')s.owner.annotations=s.owner.annotations.filter(a=>a.id!==s.a.id);else fig().annotations=fig().annotations.filter(a=>a.id!==s.a.id);state.selectedAnnotation=null;state.canvasSelection=null;renderAnnotationList();render()}
$('#legendMode').onchange=e=>{const s=selectedAnnotationObj();if(!s)return;const owner=legendOwner(s.a,s.owner);if(e.target.value==='manual'&&!s.a.manualEntries)s.a.manualEntries=legendEntries({...s.a,mode:'auto'},owner).filter(x=>x.visible!==false).map(x=>ensureLegendEntry({id:uid(),label:x.label,visible:true,color:x.color,bold:x.bold,italic:x.italic}));s.a.mode=e.target.value;renderLegendEntriesEditor(s);render()};
$('#legendBackground').onclick=()=>{const s=selectedAnnotationObj();if(!s||s.a.type!=='legend')return;s.a.background=s.a.background===false;renderAnnotationList();render()};
$('#legendSize').oninput=e=>{const s=selectedAnnotationObj();if(s){s.a.size=Math.max(8,Number(e.target.value)||14);render()}};
$('#legendScope').onchange=e=>{const s=selectedAnnotationObj();if(!s||s.scope===e.target.value)return;const pos=annotationAbs(s.a,s.scope,s.owner),a=s.a;if(s.scope==='panel')s.owner.annotations=s.owner.annotations.filter(x=>x.id!==a.id);else fig().annotations=fig().annotations.filter(x=>x.id!==a.id);if(e.target.value==='figure'){a.x=pos.x;a.y=pos.y;a.sourcePanelId=s.owner?.id||a.sourcePanelId;fig().annotations.push(a);state.selectedAnnotation={id:a.id,scope:'figure',panelId:null}}else{const owner=panel();a.x=(pos.x-owner.x)/owner.w;a.y=(pos.y-owner.y)/owner.h;a.sourcePanelId=owner.id;owner.annotations.push(a);state.selectedAnnotation={id:a.id,scope:'panel',panelId:owner.id}}renderAnnotationList();render()};
$('#addLegendLine').onclick=()=>{const s=selectedAnnotationObj();if(!s||s.a.type!=='legend')return;s.a.manualEntries=s.a.manualEntries||[];s.a.manualEntries.push(ensureLegendEntry({id:uid(),label:'Legend entry',visible:true}));renderLegendEntriesEditor(s);render()};
$('#shapeColor').oninput=e=>setShapeSetting('color',e.target.value);$('#shapeWidth').oninput=e=>setShapeSetting('width',Math.max(.25,Number(e.target.value)||1.5));$('#shapeStyle').onchange=e=>setShapeSetting('lineStyle',e.target.value);$('#shapeStartCap').onchange=e=>{setShapeSetting('startCap',e.target.value);renderAnnotationList()};$('#shapeEndCap').onchange=e=>{setShapeSetting('endCap',e.target.value);renderAnnotationList()};
$('#shapeScope').onchange=e=>{const s=selectedAnnotationObj();if(!s||s.a.type!=='shape'){if(state.drawingShape){shapeDefaults.scope=e.target.value;renderAnnotationList()}return}if(s.scope===e.target.value)return;const a=s.a,first=annotationAbs(a,s.scope,s.owner),second=s.scope==='panel'?{x:s.owner.x+a.x2*s.owner.w,y:s.owner.y+a.y2*s.owner.h}:{x:a.x2,y:a.y2};if(s.scope==='panel')s.owner.annotations=s.owner.annotations.filter(x=>x.id!==a.id);else fig().annotations=fig().annotations.filter(x=>x.id!==a.id);if(e.target.value==='figure'){a.x=first.x;a.y=first.y;a.x2=second.x;a.y2=second.y;a.sourcePanelId=s.owner?.id||a.sourcePanelId;fig().annotations.push(a);state.selectedAnnotation={id:a.id,scope:'figure',panelId:null}}else{const owner=panel();a.x=(first.x-owner.x)/owner.w;a.y=(first.y-owner.y)/owner.h;a.x2=(second.x-owner.x)/owner.w;a.y2=(second.y-owner.y)/owner.h;a.sourcePanelId=owner.id;owner.annotations.push(a);state.selectedAnnotation={id:a.id,scope:'panel',panelId:owner.id}}renderAnnotationList();render()};
$('#editLegendEntries').onclick=e=>{const box=$('#legendEntriesPopover'),open=box.classList.toggle('hidden')===false;e.currentTarget.setAttribute('aria-expanded',String(open));if(open)renderLegendEntriesEditor()};$('#closeLegendEntries').onclick=()=>{$('#legendEntriesPopover').classList.add('hidden');$('#editLegendEntries').setAttribute('aria-expanded','false')};
$('#figureHelp').onclick=e=>{const box=$('#figureHelpPopover'),open=box.classList.toggle('hidden')===false;e.currentTarget.setAttribute('aria-expanded',String(open))};$('#closeFigureHelp').onclick=()=>{$('#figureHelpPopover').classList.add('hidden');$('#figureHelp').setAttribute('aria-expanded','false')};
document.addEventListener('pointerdown',e=>{if(!e.target.closest('#figureHelpPopover,#figureHelp')){$('#figureHelpPopover').classList.add('hidden');$('#figureHelp').setAttribute('aria-expanded','false')}if(!e.target.closest('#legendEntriesPopover,#editLegendEntries')){$('#legendEntriesPopover').classList.add('hidden');$('#editLegendEntries').setAttribute('aria-expanded','false')}});
// Figures / save
$('#newFigure').onclick=()=>{const f=blankFigure(`Figure ${state.figures.length+1}`);state.figures.push(f);state.activeFigure=state.figures.length-1;state.selectedPanelId=f.panels[0].id;state.selectedCurveId=null;state.selectedTickLabels=null;state.canvasSelection='panel';syncUI();render()};
$('#duplicateFigure').onclick=()=>{const nf=structuredClone(fig()),curveMap=new Map(),panelMap=new Map();nf.id=uid();nf.name=fig().name+' copy';nf.panels.forEach(p=>{const oldPanel=p.id;p.id=uid();panelMap.set(oldPanel,p.id);p.curves=p.curves.map(c=>{const old=c.id,id=uid();curveMap.set(old,id);return{...c,id}})});nf.panels.forEach(p=>{p.curves.forEach(c=>{if(c.backgroundId&&curveMap.has(c.backgroundId))c.backgroundId=curveMap.get(c.backgroundId)});p.annotations=p.annotations.map(a=>({...a,id:uid(),sourcePanelId:panelMap.get(a.sourcePanelId)||a.sourcePanelId,entries:(a.entries||[]).map(e=>({...e,curveId:curveMap.get(e.curveId)||e.curveId}))}))});nf.annotations=nf.annotations.map(a=>({...a,id:uid(),sourcePanelId:panelMap.get(a.sourcePanelId)||a.sourcePanelId,entries:(a.entries||[]).map(e=>({...e,curveId:curveMap.get(e.curveId)||e.curveId}))}));state.figures.splice(state.activeFigure+1,0,nf);state.activeFigure++;state.selectedPanelId=nf.panels[0]?.id||null;state.selectedCurveId=null;state.selectedAnnotation=null;state.selectedTickLabels=null;state.canvasSelection='panel';syncUI();render()};
$('#renameFigure').onclick=()=>{const n=prompt('Figure name:',fig().name);if(n){fig().name=n.trim()||fig().name;renderTabs()}};
$('#deleteFigure').onclick=()=>{if(state.figures.length<=1){alert('Keep at least one figure.');return}const f=fig(),curves=f.panels.reduce((n,p)=>n+p.curves.length,0),annotations=f.annotations.length+f.panels.reduce((n,p)=>n+p.annotations.length,0);if(!confirm(`Delete “${f.name}” with ${f.panels.length} panel${f.panels.length>1?'s':''}, ${curves} curve${curves!==1?'s':''} and ${annotations} annotation${annotations!==1?'s':''}?`))return;state.figures.splice(state.activeFigure,1);state.activeFigure=clamp(state.activeFigure,0,state.figures.length-1);state.selectedPanelId=fig().panels[0]?.id||null;state.selectedCurveId=null;state.selectedAnnotation=null;state.selectedTickLabels=null;state.canvasSelection='panel';syncUI();render()};
$('#saveProject').onclick=saveProject;$('#loadProject').onchange=e=>{if(e.target.files[0])loadJsonFile(e.target.files[0],'project');e.target.value=''};$('#saveTemplate').onclick=saveTemplate;$('#loadTemplate').onchange=e=>{if(e.target.files[0])loadJsonFile(e.target.files[0],'template');e.target.value=''};$('#exportSvg').onclick=exportSvg;$('#exportPng').onclick=exportPng;
$('#undoAction').onclick=undoProject;$('#redoAction').onclick=redoProject;
window.addEventListener('keydown',e=>{const tag=e.target.tagName,editing=['INPUT','SELECT','TEXTAREA'].includes(tag)||e.target.isContentEditable,key=e.key.toLowerCase(),modifier=e.ctrlKey||e.metaKey;if(modifier&&key==='s'){e.preventDefault();saveProject();return}if(!editing&&modifier&&key==='z'){e.preventDefault();if(e.shiftKey)redoProject();else undoProject();return}if(!editing&&modifier&&key==='y'){e.preventDefault();redoProject();return}if(editing)return;if(modifier&&key==='c'&&state.canvasSelection==='annotation'){e.preventDefault();copySelectedAnnotation();return}if(modifier&&key==='v'&&annotationClipboard){e.preventDefault();pasteCopiedAnnotation();return}if(modifier&&key==='d'&&state.canvasSelection==='annotation'){e.preventDefault();if(copySelectedAnnotation())pasteCopiedAnnotation();return}if(e.key==='Escape'){state.drawingShape=null;state.selectedAnnotation=null;state.selectedTickLabels=null;state.canvasSelection=null;renderAnnotationList();render();return}const arrows={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(arrows[e.key]){e.preventDefault();const step=e.shiftKey?10:1,[dx,dy]=arrows[e.key],p=panel();if(state.canvasSelection==='ticks'&&state.selectedTickLabels){if(state.selectedTickLabels.axis==='x')p.xLabelOffsetY+=dy*step;else p.yLabelOffsetX+=dx*step}else if(state.canvasSelection==='annotation'){const s=selectedAnnotationObj();if(s){if(s.scope==='panel'){const owner=s.owner||p,rx=dx*step/owner.w,ry=dy*step/owner.h;s.a.x+=rx;s.a.y+=ry;if(s.a.type==='shape'){s.a.x2+=rx;s.a.y2+=ry}}else{s.a.x+=dx*step;s.a.y+=dy*step;if(s.a.type==='shape'){s.a.x2+=dx*step;s.a.y2+=dy*step}}}}else if(state.canvasSelection==='panel'&&!p.locked){p.x=clamp(p.x+dx*step,0,fig().width-p.w);p.y=clamp(p.y+dy*step,0,fig().height-p.h);syncGeomOnly()}render();return}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();if(state.canvasSelection==='annotation')removeSelectedObject();else if(state.canvasSelection==='panel')removeSelectedPanel()}});
document.addEventListener('input',e=>{if(!e.target.closest('#undoAction,#redoAction'))scheduleHistoryCommit(280)});
['change','click','paste','focusout'].forEach(type=>document.addEventListener(type,e=>{if(!e.target.closest('#undoAction,#redoAction'))scheduleHistoryCommit()}));
window.addEventListener('pointerup',()=>scheduleHistoryCommit());
window.addEventListener('keyup',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Delete','Backspace'].includes(e.key)||(e.ctrlKey||e.metaKey))scheduleHistoryCommit()});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flushCurrentAutosave()});
window.addEventListener('pagehide',flushCurrentAutosave);
new ResizeObserver(fitCanvas).observe($('#canvasPane'));

updateDataUI();syncUI();render();resetProjectHistory();initializeAutosave();
})();
